package local.studyplanner;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.net.Uri;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import android.text.*;
import androidx.webkit.WebViewCompat;
import androidx.webkit.WebViewFeature;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.Consumer;

/** Isolated, temporary login session. Native code receives metadata by polling, without a JS bridge. */
public class CourseImportActivity extends Activity {
    private static boolean webKitInitialized;
    WebView browser, replay;
    Dialog popup;
    LinearLayout root, results;
    EditText address, passcode, folderLimit, fileLimit, query, deadline, mergedName;
    CheckBox autoRefresh, mergeSelected;
    TextView status;
    Button importButton, refreshButton;
    final Handler handler = new Handler();
    final ExecutorService worker = Executors.newSingleThreadExecutor();
    final Map<String,String> scripts = new HashMap<>();
    final Set<String> selected = new HashSet<>();
    List<JSONObject> captures = new ArrayList<>(), xuechengBase = new ArrayList<>();
    boolean netdisk, capturing, documentStart;
    int generation;
    long lastRefresh;
    String pageTitle = "", failure = "";
    JSONObject directory;
    int observedRevision=-1;
    final Runnable passive = new Runnable(){public void run(){if(!isDestroyed()&&!netdisk&&!capturing&&browser!=null){final int current=generation;String host=Uri.parse(browser.getUrl()==null?"":browser.getUrl()).getHost();if(host!=null&&!host.endsWith("kaoyanvip.cn"))browser.evaluateJavascript("JSON.stringify(window.studyGenericCrawler?{revision:studyGenericCrawler.revision(),count:studyGenericCrawler.count(),activity:studyGenericCrawler.activity()}:null)",encoded->{if(current!=generation||capturing||isDestroyed())return;try{Object raw=new JSONTokener(encoded).nextValue();if(!(raw instanceof String))return;JSONObject value=new JSONObject((String)raw);int revision=value.getInt("revision");if(revision!=observedRevision&&value.optInt("count")>0&&value.getJSONObject("activity").optInt("pending")==0){observedRevision=revision;capture();}}catch(Exception ignored){}});}handler.postDelayed(this,3000);}};
    final Runnable refreshTimer = new Runnable() { public void run() {
        if (!isDestroyed() && autoRefresh.isChecked() && !capturing && !netdisk && System.currentTimeMillis()-lastRefresh >= 300000) capture();
        handler.postDelayed(this, 30000);
    }};

    @Override public void onCreate(Bundle saved) {
        super.onCreate(saved);
        // The manifest places this activity in its own process; do this before any WebKit API.
        if (!webKitInitialized) { if (Build.VERSION.SDK_INT >= 28) WebView.setDataDirectorySuffix("course-import"); webKitInitialized=true; }
        netdisk = "netdisk".equals(getIntent().getStringExtra("mode"));
        try { for (String name : new String[]{"CourseCrawler", "GenericCrawler", "XuechengCrawler", "XuechengReplay", "QuarkCrawler", "QuarkScan"}) scripts.put(name, MainActivity.read(getAssets().open("crawlers/"+name+".js"))); }
        catch (Exception error) { finish(); return; }
        root = column(); root.setPadding(dp(12),dp(8),dp(12),dp(8)); root.setFitsSystemWindows(true); root.setBackgroundColor(0xfff5f7fb);ScrollView content=new ScrollView(this);content.setFillViewport(true);content.addView(root);setContentView(content);
        root.addView(label(netdisk ? "夸克分享课程导入" : "网站课程导入",20));
        address = field(root,"HTTPS 网址",netdisk ? "https://pan.quark.cn/" : "https://www.kaoyanvip.cn/appmanage/my/mycourse",false);
        LinearLayout controls = row(); controls.addView(button("打开",()->open(address.getText().toString()))); controls.addView(button("默认地址",()->open(netdisk?"https://pan.quark.cn/":"https://www.kaoyanvip.cn/appmanage/my/mycourse"))); controls.addView(button("后退",()->{if(browser.canGoBack())browser.goBack();})); controls.addView(button("重新登录",this::resetSession)); controls.addView(button("关闭",this::finish)); root.addView(controls);
        if (netdisk) { LinearLayout share = row(); passcode = field(share,"提取码（可留空）","",false); passcode.setInputType(android.text.InputType.TYPE_CLASS_TEXT | android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD); folderLimit=field(share,"目录上限","60",true); fileLimit=field(share,"条目上限","2000",true); root.addView(share); }
        status=label("请在网页中登录并打开课程页面。关闭导入窗口后会清除本次登录会话。",12);root.addView(status);
        browser = webView(false); root.addView(browser,new LinearLayout.LayoutParams(-1,dp(320)));root.addView(button("展开 / 收起网页",()->browser.setVisibility(browser.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE)));
        LinearLayout actions=row(); refreshButton=button(netdisk?"读取分享目录":"抓取 / 刷新课程",this::capture);actions.addView(refreshButton);autoRefresh=new CheckBox(this);autoRefresh.setText("每5分钟刷新");autoRefresh.setVisibility(netdisk?View.GONE:View.VISIBLE);actions.addView(autoRefresh);if(netdisk)actions.addView(button("分享目录",this::directory));root.addView(actions);
        query=field(root,"搜索课程、课节或目录路径","",false);query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){renderResults();}public void afterTextChanged(Editable s){}});
        LinearLayout selectActions=row();selectActions.addView(button("勾选搜索结果",()->selectMatches(true)));selectActions.addView(button("取消搜索结果",()->selectMatches(false)));root.addView(selectActions);ScrollView scroll=new ScrollView(this);results=column();scroll.addView(results);root.addView(scroll,new LinearLayout.LayoutParams(-1,dp(240)));
        LinearLayout options=row();deadline=field(options,"新课程截止日期",LocalDate.now(Planner.ZONE).plusMonths(3).toString(),false);deadline.setFocusable(false);deadline.setOnClickListener(v->{LocalDate date;try{date=LocalDate.parse(deadline.getText().toString());}catch(Exception e){date=LocalDate.now(Planner.ZONE);}new DatePickerDialog(this,(picker,y,m,d)->deadline.setText(LocalDate.of(y,m+1,d).toString()),date.getYear(),date.getMonthValue()-1,date.getDayOfMonth()).show();});root.addView(options);
        if(netdisk){mergeSelected=new CheckBox(this);mergeSelected.setText("将所选目录合为一门课程");root.addView(mergeSelected);mergedName=field(root,"合并名称","合并课程",false);}
        LinearLayout bottom=row();bottom.addView(button("编排预览",this::preview));importButton=button("导入所选课程",this::deliver);importButton.setEnabled(false);bottom.addView(importButton);root.addView(bottom);
        handler.postDelayed(refreshTimer,30000);
        handler.postDelayed(passive,3000);
        CookieManager.getInstance().removeAllCookies(removed->{WebStorage.getInstance().deleteAllData();browser.clearCache(true);open(address.getText().toString());});
    }

    WebView webView(boolean child) {
        WebView view=new WebView(this);WebSettings settings=view.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);settings.setSupportMultipleWindows(true);settings.setJavaScriptCanOpenWindowsAutomatically(true);settings.setMediaPlaybackRequiresUserGesture(true);
        // Use desktop catalogs, which contain the complete metadata consumed by the shared crawlers.
        settings.setUserAgentString(settings.getUserAgentString().replace("; wv","").replace("Mobile ",""));
        CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(view,true);
        if(!child){try{documentStart=WebViewFeature.isFeatureSupported(WebViewFeature.DOCUMENT_START_SCRIPT);if(documentStart)WebViewCompat.addDocumentStartJavaScript(view,scripts.get("GenericCrawler"),Collections.singleton("*"));}catch(RuntimeException error){documentStart=false;}}
        view.setWebViewClient(new WebViewClient(){
            @Override public boolean shouldOverrideUrlLoading(WebView web,WebResourceRequest request){return !https(request.getUrl().toString());}
            @Override public void onPageStarted(WebView web,String url,android.graphics.Bitmap icon){if(!child){generation++;observedRevision=-1;capturing=false;refreshButton.setEnabled(true);if(netdisk){directory=null;captures.clear();selected.clear();}renderResults();if(!documentStart)web.evaluateJavascript(scripts.get("GenericCrawler"),null);}else replayURL(web,url);}
            @Override public void onPageFinished(WebView web,String url){if(child){replayURL(web,url);return;}address.setText(url);pageTitle=web.getTitle()==null?"":web.getTitle();inject(web);status.setText(documentStart?"页面已打开，可以抓取课程。":"当前系统 WebView 不支持加载前捕获：请升级 WebView，或在页面内切换课程后再抓取。研途专用抓取仍可使用。");String host=Uri.parse(url).getHost();if(!netdisk&&host!=null&&(host.equals("kaoyanvip.cn")||host.endsWith(".kaoyanvip.cn"))&&url.contains("/mycourse"))handler.postDelayed(()->{if(!capturing&&!isDestroyed())capture();},1800);}
            @Override public void onReceivedError(WebView web,WebResourceRequest request,WebResourceError error){if(request.isForMainFrame())status.setText("网页加载失败，请检查网址和网络。");}
        });
        view.setWebChromeClient(new WebChromeClient(){
            @Override public boolean onCreateWindow(WebView web,boolean dialog,boolean user,Message message){if(popup!=null){popup.dismiss();popup=null;}if(replay!=null){replay.stopLoading();replay.destroy();}replay=webView(true);if(!capturing){popup=new Dialog(CourseImportActivity.this);LinearLayout content=column();content.addView(button("关闭网页窗口",()->{if(popup!=null)popup.dismiss();}));content.addView(replay,new LinearLayout.LayoutParams(-1,0,1));popup.setContentView(content);popup.show();popup.getWindow().setLayout(-1,-1);}WebView.WebViewTransport transport=(WebView.WebViewTransport)message.obj;transport.setWebView(replay);message.sendToTarget();return true;}
            @Override public void onCloseWindow(WebView window){if(popup!=null){popup.dismiss();popup=null;}}
        });return view;
    }
    static boolean https(String url){try{Uri value=Uri.parse(url);return "https".equalsIgnoreCase(value.getScheme())&&value.getHost()!=null&&value.getUserInfo()==null;}catch(Exception error){return false;}}
    void inject(WebView web){web.evaluateJavascript("window.webkit={messageHandlers:{courseStatus:{postMessage:v=>{window.__studyStatus=String(v)}},replayMetadata:{postMessage:v=>{window.__studyReplay=v}}}};",null);for(String name:new String[]{"GenericCrawler","CourseCrawler","XuechengCrawler","QuarkCrawler","QuarkScan"})web.evaluateJavascript(scripts.get(name),null);}
    void open(String input){String url=input.trim();if(!url.contains("://"))url="https://"+url; if(!https(url)){message("请填写不含账号信息的 HTTPS 网址。");return;}browser.loadUrl(url);}
    void resetSession(){generation++;capturing=false;captures.clear();selected.clear();browser.stopLoading();CookieManager.getInstance().removeAllCookies(done->{WebStorage.getInstance().deleteAllData();browser.clearCache(true);browser.clearHistory();open(address.getText().toString());});renderResults();}
    void directory(){if(directory==null){message("请先读取分享目录。");return;}try{StringBuilder text=new StringBuilder(directory.optString("shareTitle"));for(JSONObject entry:Planner.list(directory.getJSONArray("entries")))text.append("\n\n").append(entry.optBoolean("isDirectory")?"目录 · ":"文件 · ").append(entry.optString("relativePath")).append(entry.optBoolean("isDirectory")?"":"\n"+entry.optLong("size")+" 字节"+(entry.has("durationSeconds")?" · "+Math.ceil(entry.optDouble("durationSeconds")/60)+" 分钟":""));message(text.toString());}catch(Exception error){message("目录数据不完整。");}}
    boolean matches(JSONObject snapshot,String term){StringBuilder text=new StringBuilder(snapshot.optString("name"));JSONObject net=snapshot.optJSONObject("netdisk");if(net!=null)text.append(' ').append(net.optString("folderPath"));for(JSONObject lesson:Planner.list(snapshot.optJSONArray("lessons")))text.append(' ').append(lesson.optString("name"));String haystack=text.toString().toLowerCase(Locale.ROOT);for(String word:term.split("\\s+"))if(!haystack.contains(word))return false;return true;}
    void selectMatches(boolean select){String term=query.getText().toString().trim().toLowerCase(Locale.ROOT);for(JSONObject snapshot:captures)if(matches(snapshot,term)&&importable(snapshot)){if(select)selected.add(snapshot.optString("packageID"));else selected.remove(snapshot.optString("packageID"));}renderResults();}
    boolean importable(JSONObject snapshot){return !snapshot.has("refusal")&&WebCourseImport.problem(snapshot)==null;}
    void groupChoices(){Map<String,List<JSONObject>> groups=new TreeMap<>();groups.put("全部课程",new ArrayList<>());for(JSONObject snapshot:captures)if(importable(snapshot)){groups.get("全部课程").add(snapshot);JSONObject net=snapshot.optJSONObject("netdisk");if(net==null)continue;String path=net.optString("folderPath"),parent="";String[] parts=path.split("/");for(int i=0;i<parts.length-1;i++){parent+= (parent.isEmpty()?"":"/")+parts[i];groups.computeIfAbsent(parent,k->new ArrayList<>()).add(snapshot);}}for(Map.Entry<String,List<JSONObject>> group:groups.entrySet()){if(group.getValue().isEmpty())continue;CheckBox check=new CheckBox(this);check.setText(group.getKey()+" · "+group.getValue().size()+" 门（批量选择）");boolean all=true;for(JSONObject snapshot:group.getValue())all&=selected.contains(snapshot.optString("packageID"));check.setChecked(all);check.setOnCheckedChangeListener((button,value)->{for(JSONObject snapshot:group.getValue()){if(value)selected.add(snapshot.optString("packageID"));else selected.remove(snapshot.optString("packageID"));}handler.post(this::renderResults);});results.addView(check);}}

    /** Evaluate a Promise in page memory and poll only its completed metadata envelope. */
    void promise(WebView web,String expression,long timeout,Consumer<Object> done) {
        final int current=generation;final String key="__studyCapture_"+UUID.randomUUID().toString().replace("-","");final long until=System.currentTimeMillis()+timeout;
        web.evaluateJavascript("window["+JSONObject.quote(key)+"]={pending:true};Promise.resolve().then(()=> ("+expression+")).then(value=>window["+JSONObject.quote(key)+"]={value:value}).catch(()=>window["+JSONObject.quote(key)+"]={error:true});",null);
        Runnable poll=new Runnable(){public void run(){if(isDestroyed()||current!=generation)return;if(System.currentTimeMillis()>until){failed("读取超时，请检查网络并重试。");return;}web.evaluateJavascript("JSON.stringify(Object.assign({},window["+JSONObject.quote(key)+"]||{pending:true},{status:window.__studyStatus}))",encoded->{if(isDestroyed()||current!=generation)return;try{Object outer=new JSONTokener(encoded).nextValue();if(!(outer instanceof String))throw new Exception();JSONObject value=new JSONObject((String)outer);if(value.optBoolean("pending")){if(!value.optString("status").isEmpty())status.setText(value.optString("status"));handler.postDelayed(this,350);return;}web.evaluateJavascript("delete window["+JSONObject.quote(key)+"]",null);if(value.optBoolean("error")){failed("页面读取失败。请确认已经登录、课程可见、分享提取码正确，刷新后重试。");return;}done.accept(value.opt("value"));}catch(Exception error){failed("页面返回的数据无法读取，请重试。");}});}};handler.postDelayed(poll,200);
    }
    void capture(){if(capturing)return;generation++;capturing=true;lastRefresh=System.currentTimeMillis();refreshButton.setEnabled(false);importButton.setEnabled(false);status.setText("正在读取全部课程，请保留此窗口…");failure="";inject(browser);
        if(netdisk){try{int folders=Integer.parseInt(folderLimit.getText().toString()),files=Integer.parseInt(fileLimit.getText().toString());if(folders<1||folders>500||files<1||files>20000)throw new Exception();String expression="studyQuarkScan("+JSONObject.quote(passcode.getText().toString())+","+folders+","+files+")";promise(browser,expression,600000,value->{if(!(value instanceof JSONObject)){failed("目录数据不完整。");return;}directory=(JSONObject)value;background(()->{List<JSONObject> values=NetdiskImport.build((JSONObject)value);PlannerDatabase database=new PlannerDatabase(this);try{NetdiskImport.compareExisting(values,database.load());}finally{database.close();}return values;});});}catch(Exception error){failed("目录上限须为1–500，条目上限须为1–20000。");}return;}
        String host=Uri.parse(browser.getUrl()==null?"":browser.getUrl()).getHost();
        if(host!=null&&(host.equals("kaoyanvip.cn")||host.endsWith(".kaoyanvip.cn"))){promise(browser,"studyCourseCrawler.run()",600000,value->{try{JSONObject result=(JSONObject)value;List<JSONObject> snapshots=Planner.list(result.getJSONArray("snapshots"));if(result.optJSONArray("issues")!=null&&result.getJSONArray("issues").length()>0){failed("部分课程抓取失败，请重试后再导入。");return;}for(JSONObject snapshot:snapshots)snapshot.put("fetchedAt",snapshot.getDouble("fetchedAt")-978307200);accept(snapshots);JSONArray unavailable=result.optJSONArray("unavailable");if(unavailable!=null&&unavailable.length()>0){StringBuilder text=new StringBuilder(status.getText());text.append("\n未导入的失效或不可读取课程：");for(JSONObject item:Planner.list(unavailable))text.append("\n").append(item.optString("name")).append(" · ").append(item.optString("reason"));status.setText(text.toString());}}catch(Exception error){failed("课程列表不完整。");}});}
        else {promise(browser,"(async()=>{const catalog=await studyXuechengCrawler.catalog(true);const activity=studyGenericCrawler.activity();return {catalog,responses:studyGenericCrawler.snapshot(),activity,url:location.href,title:document.title};})()",180000,value->{try{JSONObject result=(JSONObject)value;JSONObject activity=result.getJSONObject("activity");if(activity.optInt("pending")>0||activity.optInt("failed")>0){failed("网页请求尚未完成或有请求失败，请刷新后重试。");return;}List<JSONObject> generic=GenericCourseDigest.snapshots(result.getJSONArray("responses"),result.getString("url"),result.optString("title"),Planner.now());JSONObject catalog=result.optJSONObject("catalog");if(catalog==null)accept(generic);else xuecheng(catalog,generic);}catch(Exception error){failed("无法读取课程目录，请进入课程详情页后重试。");}});}
    }
    void xuecheng(JSONObject catalog,List<JSONObject> generic){try{xuechengBase=generic;JSONObject snapshot=WebsiteCapture.xuecheng(catalog,generic,browser.getUrl(),Planner.now());readReplay(snapshot,catalog.getJSONArray("rows"),0);}catch(Exception error){failed("直播目录信息不完整。");}}
    void replayURL(WebView view,String url){try{if("view.csslcloud.net".equals(Uri.parse(url).getHost())){view.evaluateJavascript("window.webkit={messageHandlers:{replayMetadata:{postMessage:v=>window.__studyReplay=v}}};"+scripts.get("XuechengReplay"),null);}else view.evaluateJavascript("(()=>{const frame=[...document.querySelectorAll('iframe')].find(f=>{try{return new URL(f.src).hostname==='view.csslcloud.net'}catch{return false}});return frame?frame.src:null})()",encoded->{try{Object raw=new JSONTokener(encoded).nextValue();if(raw instanceof String&&https((String)raw))view.loadUrl((String)raw);}catch(Exception ignored){}});}catch(Exception ignored){}}
    void readReplay(JSONObject snapshot,JSONArray rows,int index){try{while(index<rows.length()&&(!rows.getJSONObject(index).optBoolean("replay")||snapshot.getJSONArray("lessons").getJSONObject(index).has("durationSeconds")))index++;if(index==rows.length()){accept(WebsiteCapture.merge(xuechengBase,Collections.singletonList(snapshot)));return;}final int rowIndex=index;status.setText("正在读取直播回放 "+(index+1)+" / "+rows.length()+"…");if(replay!=null){replay.destroy();replay=null;}promise(browser,"studyXuechengCrawler.open("+index+")",30000,value->{if(!Boolean.TRUE.equals(value)){failed("回放入口无法打开，请重新进入课程详情页。");return;}pollReplay(snapshot,rows,rowIndex,System.currentTimeMillis()+45000,generation);});}catch(Exception error){failed("回放信息不完整。");}}
    void pollReplay(JSONObject snapshot,JSONArray rows,int index,long until,int current){if(current!=generation||isDestroyed())return;if(System.currentTimeMillis()>until){try{snapshot.getJSONArray("issues").put("回放时长未能读取："+rows.getJSONObject(index).getString("name"));readReplay(snapshot,rows,index+1);}catch(Exception error){failed("回放时长读取失败。");}return;}if(replay==null){handler.postDelayed(()->pollReplay(snapshot,rows,index,until,current),400);return;}replay.evaluateJavascript("JSON.stringify(window.__studyReplay||null)",encoded->{if(current!=generation)return;try{Object raw=new JSONTokener(encoded).nextValue();JSONObject metadata=raw instanceof String?new JSONObject((String)raw):null;if(metadata!=null&&metadata.optDouble("durationSeconds")>0&&metadata.optString("title").replaceAll("\\s+","").equals(rows.getJSONObject(index).optString("name").replaceAll("\\s+",""))){JSONObject lesson=snapshot.getJSONArray("lessons").getJSONObject(index);lesson.put("durationSeconds",metadata.getDouble("durationSeconds"));if(!lesson.has("watchedPercent")){lesson.put("watchedPercent",0);}readReplay(snapshot,rows,index+1);return;}}catch(Exception ignored){}handler.postDelayed(()->pollReplay(snapshot,rows,index,until,current),400);});}

    interface CaptureWork {List<JSONObject> run()throws Exception;}
    void background(CaptureWork work){final int current=generation;worker.execute(()->{try{List<JSONObject> data=work.run();runOnUiThread(()->{if(current==generation&&!isDestroyed())accept(data);});}catch(Exception error){runOnUiThread(()->{if(current==generation&&!isDestroyed())failed("目录识别失败："+error.getMessage());});}});}
    void accept(List<JSONObject> values){try{String host=Uri.parse(browser.getUrl()==null?"":browser.getUrl()).getHost();if(!netdisk&&host!=null&&!host.endsWith("kaoyanvip.cn"))captures=WebsiteCapture.merge(captures,values);else{captures=values;selected.clear();}capturing=false;refreshButton.setEnabled(true);status.setText("识别到 "+captures.size()+" 门课程。请选择、核对课节与进度后导入；已有课程将保留完成流水。");if(values.isEmpty())status.setText(captures.isEmpty()?"尚未捕获可排程课节，请进入课程详情并展开章节，再重新抓取。":"本轮没有新的课程，已保留此前识别的课程。");renderResults();}catch(Exception error){failed("课程合并识别失败，请重试。");}}
    void failed(String message){capturing=false;failure=message;refreshButton.setEnabled(true);captures.clear();selected.clear();status.setText(message);renderResults();}
    void renderResults(){if(results==null)return;results.removeAllViews();groupChoices();String term=query.getText().toString().trim().toLowerCase(Locale.ROOT);for(JSONObject snapshot:captures){if(!matches(snapshot,term))continue;String problem=snapshot.optString("refusal",WebCourseImport.problem(snapshot));CheckBox choice=new CheckBox(this);String id=snapshot.optString("packageID");choice.setText(snapshot.optString("name")+" · "+snapshot.optJSONArray("lessons").length()+" 课节"+(problem==null?"":"\n"+problem));choice.setEnabled(problem==null&&!capturing);choice.setChecked(selected.contains(id));choice.setOnCheckedChangeListener((button,checked)->{if(checked)selected.add(id);else selected.remove(id);importButton.setEnabled(!capturing&&!selected.isEmpty());});results.addView(choice);results.addView(button("查看课节与来源",()->details(snapshot)));JSONArray existing=snapshot.optJSONArray("existingCourses");if(existing!=null)for(JSONObject course:Planner.list(existing))results.addView(button("查看已有计划 · "+course.optString("name"),()->{setResult(RESULT_OK,new Intent().putExtra("courseID",course.optString("id")));finish();}));}importButton.setEnabled(!capturing&&!selected.isEmpty());}
    void details(JSONObject snapshot){try{StringBuilder text=new StringBuilder(snapshot.getString("name"));JSONObject net=snapshot.optJSONObject("netdisk");if(net!=null){text.append("\n").append(net.optString("detection")).append("\n缺失时长估算：").append(net.optInt("unknownDurations")).append(" 节");JSONObject dup=net.optJSONObject("duplicates");if(dup!=null)for(String key:new String[]{"groups","relatedPackages","relatedCourses","requiresReview"})for(int i=0;i<dup.optJSONArray(key).length();i++)text.append("\n").append(dup.getJSONArray(key).getString(i));}JSONObject files=snapshot.optJSONObject("netdiskLessons");for(JSONObject lesson:Planner.list(snapshot.getJSONArray("lessons"))){text.append("\n\n").append(lesson.getString("name")).append("\n").append(lesson.optBoolean("published")?"已发布":"未发布").append(" · ").append(lesson.has("durationSeconds")?Math.ceil(lesson.optDouble("durationSeconds")/60)+" 分钟":"时长未知").append(" · 进度 ").append(lesson.has("watchedPercent")?lesson.optDouble("watchedPercent")+"%":"未知");if(files!=null){JSONObject file=files.optJSONObject(lesson.optString("id"));if(file!=null)text.append("\n").append(file.optString("path")).append(" · ").append(file.optLong("size")).append(" 字节").append(file.optBoolean("estimatedDuration")?" · 估算时长":"");}}message(text.toString());}catch(Exception error){message("课程信息不完整。");}}
    List<JSONObject> chosen()throws Exception{List<JSONObject> data=new ArrayList<>();for(JSONObject capture:captures)if(selected.contains(capture.getString("packageID"))){if(capture.has("refusal")||WebCourseImport.problem(capture)!=null)throw new IllegalArgumentException("请选择完整课程。");data.add(capture);}if(data.isEmpty())throw new IllegalArgumentException("请先选择课程。");if(netdisk&&mergeSelected.isChecked())return Collections.singletonList(NetdiskImport.merge(data,mergedName.getText().toString()));return data;}
    double importDeadline(){return Planner.at(LocalDate.parse(deadline.getText().toString()),0);}
    void preview(){try{List<JSONObject> data=chosen();double date=importDeadline();ProgressDialog progress=ProgressDialog.show(this,"","正在预览…",true,false);worker.execute(()->{try{PlannerDatabase database=new PlannerDatabase(this);JSONObject state;try{state=database.load();}finally{database.close();}WebCourseImport.save(state,data,date,Planner.now());Planner.replan(state,Planner.now());Set<String> packages=new HashSet<>();for(JSONObject s:data)packages.add(s.getString("packageID"));StringBuilder text=new StringBuilder();int count=0;for(JSONObject task:Planner.list(state.getJSONArray("tasks"))){JSONObject course=Planner.course(state,task.optString("courseID"));JSONObject web=course.optJSONObject("webCourse");if(Planner.pending(task)&&web!=null&&packages.contains(web.optString("packageID"))){count++;if(count<=150)text.append(Planner.date(task.getDouble("start"))).append(" ").append(Planner.clock(Planner.planningStart(task))).append(" · ").append(task.optString("lessonName")).append("\n");}}text.append("\n合计 ").append(count).append(" 个安排；预览不保存。");JSONArray warnings=state.optJSONArray("androidWarnings");if(warnings!=null)for(int i=0;i<warnings.length();i++)text.append("\n").append(warnings.getString(i));runOnUiThread(()->{progress.dismiss();message(text.toString());});}catch(Exception error){runOnUiThread(()->{progress.dismiss();message(error.getMessage());});}});}catch(Exception error){message(error.getMessage());}}
    void deliver(){try{List<JSONObject> data=chosen();List<JSONObject> clean=new ArrayList<>();for(JSONObject snapshot:data)clean.add(WebCourseImport.cleanCapture(snapshot));JSONObject result=new JSONObject().put("snapshots",new JSONArray(clean)).put("deadline",importDeadline());File file=new File(getCacheDir(),"course-import-"+UUID.randomUUID()+".json");try(FileOutputStream output=new FileOutputStream(file)){output.write(result.toString().getBytes(StandardCharsets.UTF_8));}setResult(RESULT_OK,new Intent().putExtra("captureFile",file.getAbsolutePath()));finish();}catch(Exception error){message(error.getMessage());}}
    void message(String value){TextView text=label(value,14);text.setPadding(dp(16),dp(8),dp(16),dp(8));ScrollView scroll=new ScrollView(this);scroll.addView(text);new AlertDialog.Builder(this).setTitle("课程导入").setView(scroll).setPositiveButton("知道了",null).show();}
    int dp(int value){return (int)(value*getResources().getDisplayMetrics().density+.5f);}
    LinearLayout column(){LinearLayout layout=new LinearLayout(this);layout.setOrientation(LinearLayout.VERTICAL);return layout;}
    LinearLayout row(){LinearLayout layout=new LinearLayout(this);layout.setOrientation(LinearLayout.HORIZONTAL);return layout;}
    TextView label(String value,int size){TextView text=new TextView(this);text.setText(value);text.setTextSize(size);text.setTextColor(0xff1d2b3e);return text;}
    Button button(String title,Runnable action){Button button=new Button(this);button.setText(title);button.setTextSize(12);button.setAllCaps(false);button.setMinWidth(0);button.setMinimumWidth(0);button.setOnClickListener(v->action.run());return button;}
    EditText field(LinearLayout parent,String hint,String value,boolean numeric){EditText input=new EditText(this);input.setHint(hint);input.setText(value);input.setTextSize(13);input.setSingleLine();if(numeric)input.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);parent.addView(input,new LinearLayout.LayoutParams(parent.getOrientation()==LinearLayout.HORIZONTAL?0:-1,-2,parent.getOrientation()==LinearLayout.HORIZONTAL?1:0));return input;}
    @Override protected void onDestroy(){generation++;if(popup!=null)popup.dismiss();handler.removeCallbacksAndMessages(null);worker.shutdownNow();if(browser!=null){browser.stopLoading();browser.clearCache(true);browser.destroy();}if(replay!=null){replay.stopLoading();replay.destroy();}CookieManager.getInstance().removeAllCookies(null);WebStorage.getInstance().deleteAllData();super.onDestroy();}
}
