package local.studyplanner;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import android.text.InputType;
import android.util.AtomicFile;
import android.net.Uri;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    static final int EXPORT_BACKUP=101,IMPORT_BACKUP=102,SCAN_PAIRING_QR=103;
    JSONObject state; String syncSummary=""; LinearLayout root,body,nav; int page=0; LocalDate selected=LocalDate.now(Planner.ZONE),month=selected.withDayOfMonth(1),lastDay=selected;
    final int ink=Color.rgb(29,43,62),blue=Color.rgb(39,102,195),muted=Color.rgb(108,123,144),bg=Color.rgb(245,247,251);
    boolean busy=false,ready=false,reviewShown=false; AtomicFile storage; PlannerDatabase database; SyncWindow syncServer; String syncStatus="尚未同步"; TextView syncLabel; ExecutorService worker;Handler handler=new Handler();
    final Runnable ticker=new Runnable(){public void run(){if(ready&&!busy){LocalDate today=LocalDate.now(Planner.ZONE);if(!today.equals(lastDay)){lastDay=today;mutate(s->{},true,null);}else showReviewNotice();}handler.postDelayed(this,30000);}};
    interface Change{void run(JSONObject s)throws Exception;}
    interface Checked{void run()throws Exception;}
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(Color.WHITE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);storage=new AtomicFile(new File(getFilesDir(),"planner-v1.json"));if(b!=null){selected=LocalDate.parse(b.getString("selected",selected.toString()));month=selected.withDayOfMonth(1);page=b.getInt("page",0);}PlannerRuntime runtime=PlannerRuntime.get(this);database=runtime.database;worker=runtime.worker;
        syncServer=new SyncWindow(this,message->{syncStatus=message;updateSyncLabel();});
        IntentFilter filter=new IntentFilter(SyncWindowService.ACTION_STATUS);
        if(Build.VERSION.SDK_INT>=33)registerReceiver(syncReceiver,filter,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(syncReceiver,filter);
        TextView loading=new TextView(this);loading.setText("正在打开本地日程…");setContentView(loading);
        worker.execute(()->{try{
            JSONObject loaded;
            if(database.initialized())loaded=database.load();
            else{if(storage.getBaseFile().exists()||new File(storage.getBaseFile()+".bak").exists())loaded=new JSONObject(read(storage.openRead()));else loaded=new JSONObject(read(getAssets().open("initial-state.json")));Planner.validate(loaded);database.save(loaded);}
            JSONObject finalState=loaded;String summary=syncSummary(database.ledger());runOnUiThread(()->{state=finalState;syncSummary=summary;ready=true;render();handler.postDelayed(ticker,1000);syncServer.start(false,false);});
        }catch(Exception e){runOnUiThread(()->errorScreen(e));}});
    }
    @Override protected void onResume(){super.onResume();if(ready&&syncServer!=null){refreshSyncData();syncStatus=SyncWindowService.lastStatus;updateSyncLabel();syncServer.start(false,false);}}
    // A bounded foreground service owns the window; onStop must not invalidate pairing.

    @Override public void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putString("selected",selected.toString());b.putInt("page",page);}
    @Override public void onDestroy(){handler.removeCallbacks(ticker);unregisterReceiver(syncReceiver);super.onDestroy();}
    @Override public void onBackPressed(){if(page!=0){page=0;render();}else super.onBackPressed();}
    static String read(InputStream stream)throws Exception{try(InputStream in=stream;ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return out.toString("UTF-8");}}
    void save(JSONObject s)throws Exception{database.save(s);}

    void errorScreen(Exception e){TextView t=new TextView(this);t.setPadding(30,60,30,30);t.setText("无法打开本地日程\n\n"+e.getMessage()+"\n\n已有数据未被覆盖。请保留应用数据后重试。");setContentView(t);}
    void alert(String title,String message){new AlertDialog.Builder(this).setTitle(title).setMessage(message).setPositiveButton("知道了",null).show();}
    void run(Checked c){try{c.run();}catch(Exception e){alert("请检查",e.getMessage());}}
    void mutate(Change change,boolean replan,Runnable done){if(busy)return;busy=true;ProgressDialog progress=new ProgressDialog(this);progress.setMessage(replan?"正在保存并重新安排学习任务…":"正在保存…");progress.setCancelable(false);progress.show();worker.execute(()->{try{JSONObject next=database.load();change.run(next);if(replan)Planner.replan(next,Planner.now());Planner.validate(next);save(next);runOnUiThread(()->{state=next;busy=false;progress.dismiss();if(done!=null)done.run();render();});}catch(Exception e){runOnUiThread(()->{busy=false;progress.dismiss();alert("操作未保存",e.getMessage());});}});}
    int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    LinearLayout col(){LinearLayout v=new LinearLayout(this);v.setOrientation(1);return v;}
    LinearLayout row(){LinearLayout v=new LinearLayout(this);v.setOrientation(0);v.setGravity(Gravity.CENTER_VERTICAL);return v;}
    GradientDrawable rounded(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(4),0,dp(4));return t;}
    TextView title(String s){TextView t=text(s,20,ink);t.setTypeface(null,Typeface.BOLD);return t;}
    Button button(String s,Runnable action){Button b=new Button(this);b.setText(s);b.setTextSize(13);b.setTextColor(blue);b.setAllCaps(false);b.setMinWidth(0);b.setMinimumWidth(0);b.setMinHeight(dp(44));b.setPadding(dp(12),dp(6),dp(12),dp(6));b.setStateListAnimator(null);b.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0xffd0e1fa),rounded(0xffeef3fc,10),null));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-2,-2);bp.setMargins(dp(3),dp(3),dp(3),dp(3));b.setLayoutParams(bp);b.setOnClickListener(v->{if(!busy)action.run();});return b;}
    void weighted(LinearLayout r,View v){r.addView(v,new LinearLayout.LayoutParams(0,-2,1));}
    LinearLayout card(LinearLayout p){LinearLayout c=col();c.setPadding(dp(16),dp(12),dp(16),dp(12));c.setBackground(rounded(Color.WHITE,16));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,dp(7));p.addView(c,lp);return c;}
    void render(){if(!ready)return;root=col();root.setBackgroundColor(bg);root.setFitsSystemWindows(true);setContentView(root);LinearLayout top=row();top.setPadding(dp(20),dp(10),dp(16),dp(4));weighted(top,title("学习日程"));top.addView(button("今天",()->{selected=LocalDate.now(Planner.ZONE);month=selected.withDayOfMonth(1);page=0;render();}));root.addView(top);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);body=col();body.setPadding(dp(18),0,dp(18),dp(20));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        nav=row();nav.setPadding(dp(6),dp(5),dp(6),dp(5));nav.setBackgroundColor(Color.WHITE);String[] labels={"日历","课程","固定课表","设置"};for(int i=0;i<4;i++){final int n=i;Button b=button(labels[i],()->{page=n;render();});if(i==page){b.setTypeface(null,Typeface.BOLD);b.setBackground(rounded(0xffe7effd,12));}weighted(nav,b);}root.addView(nav);try{if(page==0)calendar();else if(page==1)courses();else if(page==2)events();else settings();}catch(Exception e){alert("显示失败",e.getMessage());}}
    int color(String c){switch(c){case "green":return 0xff168875;case "purple":return 0xff8b60ba;case "orange":return 0xffc17d30;case "pink":return 0xffc45f92;default:return blue;}}
    String hours(int n){return String.format(Locale.CHINA,"%.1f 小时",n/60.0);}
    void calendar()throws Exception{
        body.addView(text("让每一天，有条不紊",13,muted));LinearLayout c=card(body),bar=row();weighted(bar,title(month.getYear()+" 年 "+month.getMonthValue()+" 月"));bar.addView(button("‹",()->{month=month.minusMonths(1);render();}));bar.addView(button("›",()->{month=month.plusMonths(1);render();}));c.addView(bar);
        Set<LocalDate> marked=new HashSet<>();for(JSONObject t:Planner.list(state.getJSONArray("tasks")))marked.add(Planner.day(t.getDouble("start")));LinearLayout week=row();for(String w:new String[]{"一","二","三","四","五","六","日"}){TextView v=text(w,12,muted);v.setGravity(Gravity.CENTER);weighted(week,v);}c.addView(week);
        int offset=month.getDayOfWeek().getValue()-1;LocalDate first=month.minusDays(offset);for(int r=0;r<6;r++){LinearLayout rr=row();for(int j=0;j<7;j++){LocalDate d=first.plusDays(r*7+j);boolean mark=marked.contains(d);if(!mark)for(JSONObject e:Planner.list(state.getJSONArray("fixedEvents")))if(Planner.occurs(e,d)){mark=true;break;}TextView v=text(d.getDayOfMonth()+(mark?"\n·":"\n "),14,d.getMonth()==month.getMonth()?ink:0xffb3bdcb);v.setGravity(Gravity.CENTER);v.setMinHeight(dp(43));v.setContentDescription(d.toString()+(mark?" 有安排":""));if(d.equals(selected)){v.setTextColor(Color.WHITE);v.setBackground(rounded(blue,10));}else if(d.equals(LocalDate.now(Planner.ZONE)))v.setTextColor(blue);v.setOnClickListener(x->{selected=d;render();});weighted(rr,v);}c.addView(rr);if(!first.plusDays((r+1)*7).isBefore(month.plusMonths(1)))break;}
        List<JSONObject> review=Planner.review(state,Planner.now());if(!review.isEmpty())body.addView(button("学习完成确认 · "+review.size()+" 项待确认",this::review));JSONArray warnings=state.optJSONArray("androidWarnings");if(warnings!=null&&warnings.length()>0){LinearLayout w=card(body);w.addView(text("排程需要调整",16,0xffb06a13));for(int i=0;i<warnings.length();i++)w.addView(text(warnings.getString(i),13,muted));}
        LinearLayout head=row();weighted(head,title(selected.getMonthValue()+" 月 "+selected.getDayOfMonth()+" 日 · "+new String[]{"一","二","三","四","五","六","日"}[selected.getDayOfWeek().getValue()-1]));head.addView(button("‹",()->{selected=selected.minusDays(1);month=selected.withDayOfMonth(1);render();}));head.addView(button("›",()->{selected=selected.plusDays(1);month=selected.withDayOfMonth(1);render();}));body.addView(head);
        List<JSONObject> tasks=new ArrayList<>(),events=new ArrayList<>();int planned=0,done=0;for(JSONObject t:Planner.list(state.getJSONArray("tasks")))if(Planner.day(t.getDouble("start")).equals(selected)){JSONObject owner=Planner.course(state,t.getString("courseID"));if(!owner.optBoolean("isArchived")||!Planner.pending(t)){tasks.add(t);if(Planner.pending(t))planned+=t.getInt("durationMinutes");}}for(JSONObject e:Planner.list(state.getJSONArray("fixedEvents")))if(Planner.occurs(e,selected))events.add(e);for(JSONObject e:Planner.list(state.getJSONArray("completions")))if(Planner.day(e.getDouble("recordedAt")).equals(selected))done+=e.getInt("minutes");body.addView(text("待学 "+hours(planned)+"   已确认 "+hours(done)+"   固定 "+events.size()+" 项",12,muted));
        List<JSONObject> timeline=new ArrayList<>(events);for(JSONObject t:tasks)if(Planner.pending(t))timeline.add(t);timeline.sort(Comparator.comparingDouble(t->t.has("courseID")?t.optDouble("start"):Planner.at(selected,t.optInt("startMinute"))));for(JSONObject item:timeline){if(item.has("courseID"))taskCard(body,item);else eventCard(body,item,false);}if(timeline.isEmpty())card(body).addView(text("这一天没有待进行的安排",15,muted));boolean label=false;for(JSONObject t:tasks)if(!Planner.pending(t)){if(!label){body.addView(title("完成记录"));label=true;}taskCard(body,t);}body.addView(button("重新排程",()->mutate(s->{},true,null)));
    }
    void taskCard(LinearLayout parent,JSONObject t)throws Exception{JSONObject c=Planner.course(state,t.getString("courseID"));LinearLayout box=card(parent);box.addView(text(Planner.clock(t.getDouble("start"))+" — "+Planner.clock(Planner.end(t))+"   "+t.getInt("durationMinutes")+" 分钟",12,muted));TextView name=text(c.getString("name"),17,color(c.optString("color")));name.setTypeface(null,Typeface.BOLD);box.addView(name);if(Planner.pending(t)){LinearLayout actions=row();weighted(actions,button(t.getDouble("start")>Planner.now()?"提前完成":"全部完成",()->mutate(s->Planner.confirm(s,t.optString("id"),t.optInt("durationMinutes"),Planner.now()),false,null)));weighted(actions,button("部分 / 未完成",()->completion(t)));box.addView(actions);}else{LinearLayout result=row();weighted(result,text(t.optString("status").equals("missed")?"未完成 · 已保留剩余学习量":"已确认 "+t.optInt("completedMinutes")+" 分钟",13,muted));result.addView(button("撤销",()->mutate(s->Planner.undoConfirmation(s,t.optString("id"),Planner.now()),!t.optString("status").equals("completed"),null)));box.addView(result);}}
    void completion(JSONObject t){LinearLayout form=col();form.setPadding(dp(20),dp(8),dp(20),0);EditText actual=field(form,"实际完成分钟（0 = 未完成）",""+t.optInt("durationMinutes"),true);AlertDialog d=new AlertDialog.Builder(this).setTitle("确认学习进度").setView(form).setNegativeButton("取消",null).setPositiveButton("确认",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(x->run(()->{int n=Integer.parseInt(actual.getText().toString());if(n<0||n>t.getInt("durationMinutes"))throw new Exception("实际时长超出计划范围");mutate(s->Planner.confirm(s,t.getString("id"),n,Planner.now()),n!=t.getInt("durationMinutes"),d::dismiss);})));d.show();}
    void review(){LinearLayout list=col();list.setPadding(dp(16),0,dp(16),dp(16));Map<String,EditText> values=new LinkedHashMap<>();for(JSONObject t:Planner.review(state,Planner.now())){JSONObject c=Planner.course(state,t.optString("courseID"));EditText e=field(list,Planner.date(t.optDouble("start"))+" "+Planner.clock(t.optDouble("start"))+" · "+c.optString("name")+"（最多 "+t.optInt("durationMinutes")+" 分钟）","",true);e.setHint("留空暂不确认，0 表示未完成");values.put(t.optString("id"),e);}ScrollView sv=new ScrollView(this);sv.addView(list);AlertDialog d=new AlertDialog.Builder(this).setTitle("逐项确认实际学习分钟").setView(sv).setNegativeButton("稍后",null).setPositiveButton("保存已填写项",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(x->run(()->{Map<String,Integer> filled=new HashMap<>();for(Map.Entry<String,EditText> e:values.entrySet()){String a=e.getValue().getText().toString().trim();if(!a.isEmpty())filled.put(e.getKey(),Integer.parseInt(a));}if(filled.isEmpty())throw new Exception("请至少填写一项");boolean needsReplan=false;for(JSONObject task:Planner.review(state,Planner.now()))if(filled.containsKey(task.optString("id"))&&filled.get(task.optString("id"))!=task.optInt("durationMinutes"))needsReplan=true;mutate(s->{double now=Planner.now();for(Map.Entry<String,Integer> e:filled.entrySet())Planner.confirm(s,e.getKey(),e.getValue(),now);},needsReplan,d::dismiss);})));d.show();}
    void showReviewNotice(){if(!reviewShown&&!Planner.review(state,Planner.now()).isEmpty()){reviewShown=true;render();}}
    void courses()throws Exception{body.addView(title("课程管理"));body.addView(text("学习量、截止日期与课程进度",13,muted));body.addView(button("＋ 添加课程",()->courseEditor(null)));List<JSONObject> cs=Planner.list(state.getJSONArray("courses"));cs.sort(Comparator.comparingDouble(c->c.optDouble("deadline")));for(JSONObject c:cs)if(!c.optBoolean("isArchived")){LinearLayout box=card(body);box.addView(text(c.getString("name"),19,color(c.optString("color"))));int done=Planner.completed(state,c),total=c.getInt("totalMinutes");box.addView(text(hours(done)+" / "+hours(total)+" · 截止 "+Planner.date(c.getDouble("deadline")),13,muted));ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(Math.max(1,total));p.setProgress(done);box.addView(p);int days=(int)Math.max(1,java.time.temporal.ChronoUnit.DAYS.between(LocalDate.now(Planner.ZONE),Planner.day(c.getDouble("deadline")))+1);box.addView(text("剩余 "+hours(Planner.remaining(state,c))+" · 平均每天约 "+(int)Math.ceil(Planner.remaining(state,c)/(double)days)+" 分钟",13,muted));if(!c.optString("notes").isEmpty())box.addView(text(c.optString("notes"),13,ink));box.addView(button("编辑课程",()->courseEditor(c)));}}
    EditText field(LinearLayout p,String label,String value,boolean number){p.addView(text(label,13,muted));EditText e=new EditText(this);e.setText(value);e.setTextSize(16);e.setSingleLine(true);e.setPadding(dp(6),dp(8),dp(6),dp(8));if(number)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);p.addView(e,new LinearLayout.LayoutParams(-1,-2));return e;}
    EditText dateField(LinearLayout p,String label,String value){EditText e=field(p,label,value,false);e.setFocusable(false);e.setOnClickListener(v->{LocalDate d=LocalDate.parse(e.getText().toString());new DatePickerDialog(this,(picker,y,m,day)->e.setText(LocalDate.of(y,m+1,day).toString()),d.getYear(),d.getMonthValue()-1,d.getDayOfMonth()).show();});return e;}
    Spinner spinner(LinearLayout p,String label,String[] options,int selected){p.addView(text(label,13,muted));Spinner v=new Spinner(this);ArrayAdapter<String> a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,options);v.setAdapter(a);v.setSelection(Math.max(0,selected));p.addView(v);return v;}
    AlertDialog editor(String title,LinearLayout form){ScrollView sv=new ScrollView(this);form.setPadding(dp(22),dp(8),dp(22),dp(24));sv.addView(form);return new AlertDialog.Builder(this).setTitle(title).setView(sv).setNegativeButton("取消",null).setPositiveButton("保存",null).create();}
    String value(EditText e){return e.getText().toString().trim();}int integer(EditText e){return Integer.parseInt(value(e));}double dateValue(EditText e){return Planner.at(LocalDate.parse(value(e)),0);}int minutes(EditText e){double n=Double.parseDouble(value(e));if(!Double.isFinite(n)||n<0||n>100000)throw new IllegalArgumentException("小时数应在 0–100000 之间");return (int)Math.round(n*60);}
    void courseEditor(JSONObject original){run(()->{JSONObject c=original==null?new JSONObject().put("id",Planner.id()).put("name","").put("totalMinutes",60).put("initialCompletedMinutes",0).put("startDate",Planner.at(selected,0)).put("deadline",Planner.at(selected.plusDays(30),0)).put("minimumBlockMinutes",60).put("autoScheduleEnabled",true).put("priority",2).put("type","录播课程").put("color","blue").put("isArchived",false).put("notes",""):new JSONObject(original.toString());LinearLayout f=col();EditText name=field(f,"课程名称",c.optString("name"),false);String[] types={"录播课程","补习回放","其他学习"};Spinner type=spinner(f,"类型",types,Arrays.asList(types).indexOf(c.optString("type")));EditText total=field(f,"总学习量（小时）",""+c.optInt("totalMinutes")/60.0,true),initial=field(f,"导入前已完成量（小时，不含应用内记录）",""+c.optInt("initialCompletedMinutes")/60.0,true);EditText start=dateField(f,"开始日期",Planner.date(c.getDouble("startDate"))),deadline=dateField(f,"截止日期（包含当天）",Planner.date(c.getDouble("deadline")));CheckBox published=new CheckBox(this);published.setText("设置发布时间");published.setChecked(c.has("publishedDate"));f.addView(published);EditText publish=dateField(f,"发布时间",Planner.date(c.optDouble("publishedDate",c.getDouble("startDate"))));Spinner priority=spinner(f,"优先级",new String[]{"低","中","高"},c.optInt("priority",2)-1);EditText block=field(f,"最小时间块（分钟，0 跟随全局）",""+c.optInt("minimumBlockMinutes"),true);String[] keys={"blue","green","purple","orange","pink"};Spinner color=spinner(f,"颜色",new String[]{"蓝色","绿色","紫色","橙色","粉色"},Arrays.asList(keys).indexOf(c.optString("color")));CheckBox auto=new CheckBox(this);auto.setText("自动排程");auto.setChecked(c.optBoolean("autoScheduleEnabled",true));f.addView(auto);EditText notes=field(f,"备注",c.optString("notes"),false);notes.setSingleLine(false);AlertDialog d=editor(original==null?"添加课程":"编辑课程",f);if(original!=null)f.addView(button("归档课程",()->new AlertDialog.Builder(this).setTitle("归档此课程？").setMessage("停止未来排程，保留历史与完成记录。").setNegativeButton("取消",null).setPositiveButton("归档",(a,b)->mutate(s->Planner.course(s,c.getString("id")).put("isArchived",true),true,d::dismiss)).show()));d.setOnShowListener(v->d.getButton(-1).setOnClickListener(x->run(()->{if(value(name).isEmpty())throw new Exception("请填写课程名称");int t=minutes(total),i=minutes(initial),u=integer(block);if(t<=0||i>t||u<0||u>1440)throw new Exception("学习量或最小时间块无效");double a=dateValue(start),b=dateValue(deadline);if(b<a)throw new Exception("截止日期早于开始日期");c.put("name",value(name)).put("type",types[type.getSelectedItemPosition()]).put("totalMinutes",t).put("initialCompletedMinutes",i).put("startDate",a).put("deadline",b).put("minimumBlockMinutes",u).put("priority",priority.getSelectedItemPosition()+1).put("color",keys[color.getSelectedItemPosition()]).put("autoScheduleEnabled",auto.isChecked()).put("notes",value(notes));if(published.isChecked())c.put("publishedDate",dateValue(publish));else c.remove("publishedDate");mutate(s->Planner.put(s.getJSONArray("courses"),c),true,d::dismiss);})));d.show();});}
    String repeat(JSONObject e){JSONArray w=e.optJSONArray("weekdays");if(w==null||w.length()==0)return "单次";String[] names={"","日","一","二","三","四","五","六"};List<Integer> a=new ArrayList<>();for(int i=0;i<w.length();i++)a.add(w.optInt(i));Collections.sort(a);String r="每周 ";for(int i:a)r+=names[i]+" ";return r;}
    void eventCard(LinearLayout parent,JSONObject e,boolean detail)throws Exception{LinearLayout box=card(parent);box.addView(text(Planner.time(e.getInt("startMinute"))+" — "+Planner.time(e.getInt("endMinute"))+" · 固定事项",12,muted));box.addView(text(e.getString("title"),17,color(e.optString("color","orange"))));if(detail)box.addView(text(repeat(e)+"\n"+Planner.date(e.getDouble("startDate"))+" 至 "+Planner.date(e.getDouble("endDate")),12,muted));if(!e.optString("notes").isEmpty())box.addView(text(e.optString("notes"),13,muted));box.addView(button("编辑事项",()->eventEditor(e)));}
    void events()throws Exception{body.addView(title("固定课表"));body.addView(text("固定课程和休息时间优先保留",13,muted));body.addView(button("＋ 添加固定事项",()->eventEditor(null)));List<JSONObject> es=Planner.list(state.getJSONArray("fixedEvents"));es.sort(Comparator.comparingDouble(e->e.optDouble("startDate")));int hidden=0;for(JSONObject e:es){if(Planner.day(e.getDouble("endDate")).isBefore(LocalDate.now(Planner.ZONE))){hidden++;continue;}eventCard(body,e,true);}body.addView(text("另有 "+hidden+" 条历史规则，已保留在数据中。",12,muted));}
    void eventEditor(JSONObject original){run(()->{JSONObject e=original==null?new JSONObject().put("id",Planner.id()).put("title","").put("startMinute",480).put("endMinute",540).put("startDate",Planner.at(selected,0)).put("endDate",Planner.at(selected.plusDays(112),0)).put("weekdays",new JSONArray()).put("excludedDates",new JSONArray()).put("color","orange").put("notes",""):new JSONObject(original.toString());LinearLayout f=col();EditText title=field(f,"事项名称",e.optString("title"),false),start=field(f,"开始时间（HH:mm）",Planner.time(e.getInt("startMinute")),false),end=field(f,"结束时间（HH:mm）",Planner.time(e.getInt("endMinute")),false),first=dateField(f,"开始日期",Planner.date(e.getDouble("startDate"))),last=dateField(f,"结束日期",Planner.date(e.getDouble("endDate")));f.addView(text("重复星期（不选为单次）",13,muted));CheckBox[] checks=new CheckBox[7];String[] names={"星期日","星期一","星期二","星期三","星期四","星期五","星期六"};for(int i=0;i<7;i++){checks[i]=new CheckBox(this);checks[i].setText(names[i]);for(int j=0;j<e.getJSONArray("weekdays").length();j++)if(e.getJSONArray("weekdays").getInt(j)==i+1)checks[i].setChecked(true);f.addView(checks[i]);}String excluded="";JSONArray exc=e.optJSONArray("excludedDates");if(exc!=null)for(int i=0;i<exc.length();i++)excluded+=Planner.date(exc.getDouble(i))+" ";EditText exclusions=field(f,"跳过日期（YYYY-MM-DD，空格分隔）",excluded.trim(),false);exclusions.setSingleLine(false);EditText notes=field(f,"备注",e.optString("notes"),false);String[] keys={"blue","green","purple","orange","pink"};Spinner color=spinner(f,"颜色",new String[]{"蓝色","绿色","紫色","橙色","粉色"},Arrays.asList(keys).indexOf(e.optString("color")));AlertDialog d=editor(original==null?"添加固定事项":"编辑固定事项",f);if(original!=null)f.addView(button("删除未来安排",()->new AlertDialog.Builder(this).setTitle("删除此事项的未来安排？").setMessage("历史和今天已开始的安排会保留。").setNegativeButton("取消",null).setPositiveButton("删除",(a,b)->mutate(s->Planner.removeEvent(s,e.getString("id"),Planner.now()),true,d::dismiss)).show()));d.setOnShowListener(v->d.getButton(-1).setOnClickListener(x->run(()->{if(value(title).isEmpty())throw new Exception("请填写事项名称");JSONArray weeks=new JSONArray(),ex=new JSONArray();for(int i=0;i<7;i++)if(checks[i].isChecked())weeks.put(i+1);if(!value(exclusions).isEmpty())for(String token:value(exclusions).split("[\\s,，]+"))ex.put(Planner.at(LocalDate.parse(token),0));double a=dateValue(first),b=weeks.length()==0?a:dateValue(last);e.put("title",value(title)).put("startMinute",Planner.minute(value(start))).put("endMinute",Planner.minute(value(end))).put("startDate",a).put("endDate",b).put("weekdays",weeks).put("excludedDates",ex).put("notes",value(notes)).put("color",keys[color.getSelectedItemPosition()]);mutate(s->Planner.saveEvent(s,e,Planner.now()),true,d::dismiss);})));d.show();});}
    void settings()throws Exception{body.addView(title("学习设置"));syncSettings();body.addView(text("所有数据离线保存在手机，可通过手机热点与 Mac 同步。",13,muted));JSONObject settings=state.getJSONObject("settings");LinearLayout f=card(body);EditText unit=field(f,"全局最小学习时间块（分钟）",""+settings.getInt("minimumScheduleUnit"),true),notification=field(f,"应用内每日确认时间（HH:mm）",Planner.time(settings.getInt("notificationMinute")),false);f.addView(text("可学习时段 · 每行支持多个时段，以逗号分隔；留空为休息日。",13,muted));EditText[] availability=new EditText[7];for(int i=0;i<7;i++){int weekday=(i+1)%7+1;String v="";for(JSONObject a:Planner.list(settings.getJSONArray("availability")))if(a.getInt("weekday")==weekday)v+=(v.isEmpty()?"":", ")+Planner.time(a.getInt("startMinute"))+"-"+Planner.time(a.getInt("endMinute"));availability[i]=field(f,"星期"+new String[]{"一","二","三","四","五","六","日"}[i],v,false);availability[i].setHint("08:00-12:00, 14:00-22:00");}f.addView(button("保存设置并重排",()->run(()->{int n=integer(unit),time=Planner.minute(value(notification));if(n<1||n>1440||time>=1440)throw new Exception("时间块或确认时间无效");JSONArray windows=new JSONArray();for(int i=0;i<7;i++){String line=value(availability[i]);if(line.isEmpty())continue;for(String token:line.split("[,，]")){String[] parts=token.trim().split("-");if(parts.length!=2)throw new Exception("时段格式应为 08:00-12:00");int a=Planner.minute(parts[0]),b=Planner.minute(parts[1]);if(a>=b)throw new Exception("时段结束必须晚于开始");windows.put(new JSONObject().put("id",Planner.id()).put("weekday",(i+1)%7+1).put("startMinute",a).put("endMinute",b));}}mutate(s->s.put("settings",new JSONObject().put("minimumScheduleUnit",n).put("notificationMinute",time).put("availability",windows)),true,null);})));LinearLayout backup=card(body);backup.addView(title("数据与备份"));backup.addView(text("安装包不含个人日程；首次安装以空白日程开始。覆盖安装不会替换手机进度。卸载会删除手机数据，请先导出备份。",13,muted));backup.addView(button("导出手机日程备份",()->{Intent intent=new Intent(Intent.ACTION_CREATE_DOCUMENT);intent.setType("application/json");intent.addCategory(Intent.CATEGORY_OPENABLE);intent.putExtra(Intent.EXTRA_TITLE,"学习日程-"+LocalDate.now(Planner.ZONE)+".json");startActivityForResult(intent,EXPORT_BACKUP);}));backup.addView(button("从备份恢复",()->{Intent intent=new Intent(Intent.ACTION_OPEN_DOCUMENT);intent.setType("application/json");intent.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(intent,IMPORT_BACKUP);}));JSONObject meta=new JSONObject(read(getAssets().open("snapshot-info.json")));backup.addView(text("初始数据："+meta.getJSONObject("counts").getInt("courses")+" 门课程 · "+meta.getJSONObject("counts").getInt("fixedEvents")+" 条固定规则 · "+meta.getJSONObject("counts").getInt("tasks")+" 条任务 · "+meta.getJSONObject("counts").getInt("completions")+" 条完成记录\n安卓版 1.3 · Android 8.0 及以上",12,muted));}
    final BroadcastReceiver syncReceiver=new BroadcastReceiver(){public void onReceive(Context c,Intent i){syncStatus=SyncWindowService.lastStatus;updateSyncLabel();if(i.getBooleanExtra("changed",false))refreshSyncData();}};
    void refreshSyncData(){if(!ready)return;worker.execute(()->{try{JSONObject latest=database.load();String summary=syncSummary(database.ledger());runOnUiThread(()->{if(isDestroyed())return;state=latest;syncSummary=summary;render();});}catch(Exception e){runOnUiThread(()->{syncStatus="读取同步结果失败："+e.getMessage();updateSyncLabel();});}});}
    static String syncSummary(SyncLedger ledger){double time=ledger.value.optDouble("lastSuccess",0);return "今日自动同步："+(LocalDate.now(Planner.ZONE).toString().equals(ledger.value.optString("lastAutoDate"))?"已完成":"尚未完成")+"\n最后同步："+(time>0?Instant.ofEpochSecond((long)time).atZone(Planner.ZONE).format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")):"尚无");}
    void updateSyncLabel(){if(syncLabel!=null)syncLabel.setText(syncStatus+"\n"+syncSummary);}
    void syncSettings()throws Exception{
        LinearLayout box=card(body);box.addView(title("热点局域网同步"));syncLabel=text("",13,muted);syncLabel.setTextIsSelectable(true);box.addView(syncLabel);updateSyncLabel();
        box.addView(text("Mac 连接本机热点后同步。首次配对请扫描 Mac 生成的二维码；二维码不含日程内容。接收窗口最长 120 秒，完成或超时后自动关闭。",13,muted));
        box.addView(button("立即同步 · 开启接收窗口",()->syncServer.start(false,true)));
        box.addView(button("扫描 Mac 配对二维码",()->{if(syncServer.isRunning()){syncStatus="请先关闭当前接收窗口，再扫描二维码";updateSyncLabel();}else startActivityForResult(new Intent(this,QrScannerActivity.class),SCAN_PAIRING_QR);}));
        box.addView(button("关闭接收窗口",()->syncServer.close()));
        box.addView(button("查看同步日志",()->run(()->{File file=new File(getFilesDir(),"sync.log");alert("同步日志",file.exists()?read(new FileInputStream(file)):"暂无日志");})));
    }
    static String pairingSecret(String payload)throws Exception{Uri uri=Uri.parse(payload);if(!"studyplanner".equals(uri.getScheme())||!"pair".equals(uri.getHost())||!"2".equals(uri.getQueryParameter("v")))throw new Exception("这不是学习日程配对二维码");String secret=uri.getQueryParameter("secret"),expires=uri.getQueryParameter("expires");if(secret==null||!secret.matches("[0-9a-fA-F]{64}")||expires==null)throw new Exception("配对二维码内容无效");long expiry=Long.parseLong(expires)*1000L,now=System.currentTimeMillis();if(expiry<=now||expiry-now>600000)throw new Exception("配对二维码已过期，请在 Mac 重新生成");return secret.toLowerCase(Locale.ROOT);}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null)return;run(()->{if(request==SCAN_PAIRING_QR){String payload=data.getStringExtra(QrScannerActivity.EXTRA_RESULT);if(payload==null)throw new Exception("没有读取到二维码");syncServer.startPairing(pairingSecret(payload));}else if(request==EXPORT_BACKUP&&data.getData()!=null){try(OutputStream out=getContentResolver().openOutputStream(data.getData())){out.write(state.toString(2).getBytes(StandardCharsets.UTF_8));}Toast.makeText(this,"备份已导出",Toast.LENGTH_LONG).show();}else if(request==IMPORT_BACKUP&&data.getData()!=null){JSONObject imported=new JSONObject(read(getContentResolver().openInputStream(data.getData())));Planner.validate(imported);new AlertDialog.Builder(this).setTitle("恢复此备份？").setMessage("将替换手机当前日程。建议先导出当前备份。\n备份包含 "+imported.getJSONArray("courses").length()+" 门课程、"+imported.getJSONArray("tasks").length()+" 条任务。").setNegativeButton("取消",null).setPositiveButton("恢复",(a,b)->mutate(s->{Iterator<String> keys=s.keys();List<String> names=new ArrayList<>();while(keys.hasNext())names.add(keys.next());for(String k:names)s.remove(k);Iterator<String> incoming=imported.keys();while(incoming.hasNext()){String k=incoming.next();s.put(k,imported.get(k));}},false,null)).show();}});}
}
