package local.studyplanner;

import org.json.*;import java.util.*;import java.util.regex.*;

/** Read-only folder recognition and conservative duplicate review. Tokens never enter these records. */
public final class NetdiskImport {
 static class Folder {String path,name,fid;List<Folder> children=new ArrayList<>();List<JSONObject> own=new ArrayList<>(),videos=new ArrayList<>();int documents,others;double score;Folder(String path,String name,String fid){this.path=path;this.name=name;this.fid=fid;}}
 static final String VIDEO="mp4|mkv|mov|avi|flv|webm|m4v|ts|wmv|rmvb|rm|mpeg|mpg|f4v|3gp|vob|m2ts|mts|asf|ogv|m3u8|mpd";
 static final String DOCUMENT="pdf|doc|docx|ppt|pptx|xls|xlsx|txt|md|epub|mobi|caj|djvu|rtf|csv|pages|numbers|key|wps|et|dps";
 static final String[] COURSE_WORDS={"课程","视频","课","讲","精讲","强化","基础","冲刺","真题","习题","刷题","直播","回放","伴学","集训","点睛","押题","导学","串讲","考点","题型","网课","教程","lecture","lesson","course","video"};
 static final String[] STAGES={"抢跑","预备","入门","基础","核心","强化","精讲","定制","题型","通法","集训","寒假","暑假","春季","秋季","冲刺","真题","阶段","模考","押题","伴学","刷题","选学"};
 static final String[] MATERIAL={"资料","讲义","课件","笔记","书籍","电子书","答案","解析"};
 static boolean has(String name,String[] words){for(String word:words)if(name.toLowerCase(Locale.ROOT).contains(word))return true;return false;}
 static String extension(String name){int dot=name.lastIndexOf('.');return dot>=0?name.substring(dot+1).toLowerCase(Locale.ROOT):"";}
 static boolean video(JSONObject item){return !item.optBoolean("isDirectory")&&(extension(item.optString("name")).matches(VIDEO)||(item.optInt("category")==1||item.optInt("category")==9)||item.optString("formatType").toLowerCase(Locale.ROOT).contains("video"));}
 static boolean playable(JSONObject item){return item.optInt("status",1)==1&&!item.optBoolean("banned")&&!item.optBoolean("badContent")&&item.optInt("riskType")==0;}
 static Double duration(JSONObject item){double value=item.optDouble("durationSeconds",Double.NaN);return Double.isFinite(value)&&value>=1&&value<=36000?value:null;}
 static String title(String name){return name.replaceAll("\\.[A-Za-z0-9]{1,5}$","").trim();}
 static String loose(String name){return java.text.Normalizer.normalize(title(name),java.text.Normalizer.Form.NFKC).toLowerCase(Locale.ROOT).replaceAll("(?<![0-9])(?:2160|1440|1080|720|480)[pi]|[248]k|[hx]26[45]|高清|超清|蓝光|副本|复制|\\(\\d+\\)$","").replaceAll("[\\s._\\-—、()\\[\\]]","");}
 static boolean chapter(String name){return name.matches(".*第[零〇一二三四五六七八九十百两0-9]+章.*")||name.contains("章节")||name.toLowerCase(Locale.ROOT).contains("chapter");}
 static int episode(String name){Matcher m=Pattern.compile("第?([0-9]+)[讲节课集章]?|第([零〇一二三四五六七八九十百两]+)[讲节课集章]").matcher(name);if(!m.find())return 0;try{return m.group(1)!=null?Integer.parseInt(m.group(1)):CourseTools.chinese(m.group(2));}catch(Exception e){return 0;}}
 static void collect(Folder folder){folder.videos.addAll(folder.own);for(Folder child:folder.children){collect(child);folder.videos.addAll(child.videos);folder.documents+=child.documents;folder.others+=child.others;}int count=folder.videos.size(),numbered=0;Set<Integer> episodes=new HashSet<>();double seconds=0;for(JSONObject video:folder.videos){int n=episode(video.optString("name"));if(n>0){numbered++;episodes.add(n);}Double d=duration(video);if(d!=null)seconds+=d;}double sequence=count<2?(count==0?0:.3):(numbered/(double)count*.7+episodes.size()/(double)Math.max(1,numbered)*.3);double name=has(folder.name,COURSE_WORDS)?.55:0;if(has(folder.name,MATERIAL))name-=.35;if(episode(folder.name)>0)name+=.2;name=Math.max(0,Math.min(1,name));double volume=Math.min(1,count/3.0*.5+Math.min(1,(seconds>0?seconds:count*300)/3600)*.5);folder.score=count/(double)Math.max(1,count+folder.documents+folder.others)*.4+sequence*.2+name*.2+volume*.2;if(folder.documents>count)folder.score=Math.min(folder.score,.5);if(count<3)folder.score=Math.min(folder.score,.55);}
 static long bytes(List<JSONObject> videos){long total=0;for(JSONObject item:videos)total+=Math.max(0,item.optLong("size"));return total;}
 static int quality(JSONObject item){int height=Math.min(item.optInt("width"),item.optInt("height"));if(height==0){Matcher resolution=Pattern.compile("(2160|1440|1080|720|480)[pi]",Pattern.CASE_INSENSITIVE).matcher(item.optString("name"));if(resolution.find())height=Integer.parseInt(resolution.group(1));}return height;}
 static double ratio(double a,double b){double high=Math.max(a,b);return high<=0?1:Math.min(a,b)/high;}
 static double seconds(List<JSONObject> videos){double total=0;for(JSONObject item:videos){Double d=duration(item);if(d!=null)total+=d;}return total;}
 static Set<String> identities(List<JSONObject> videos){Set<String> names=new HashSet<>();for(JSONObject v:videos){String name=loose(v.optString("name"));if(name.length()>=2&&!name.matches("第?[0-9]+[题讲课节集章](?:视频)?(?:讲解|解析|测试)?")&&!Arrays.asList("视频","课程","讲解","答案","解析","习题","测试","课件").contains(name))names.add(name);}return names;}
 static JSONObject summary(){try{return new JSONObject().put("groups",new JSONArray()).put("removedVideos",0).put("relatedPackages",new JSONArray()).put("relatedCourses",new JSONArray()).put("requiresReview",new JSONArray());}catch(Exception e){throw new IllegalStateException(e);}}
 static List<JSONObject> dedup(List<JSONObject> videos,JSONObject report)throws Exception{
  Map<String,List<JSONObject>> buckets=new LinkedHashMap<>();for(JSONObject v:videos){String key=v.optString("parentPath")+"|"+loose(v.optString("name"));buckets.computeIfAbsent(key,k->new ArrayList<>()).add(v);}List<JSONObject> kept=new ArrayList<>();int removed=0;for(List<JSONObject> bucket:buckets.values()){bucket.sort((a,b)->{int rank=Integer.compare(quality(b),quality(a));if(rank==0)rank=Double.compare(b.optDouble("durationSeconds"),a.optDouble("durationSeconds"));if(rank==0)rank=Long.compare(b.optLong("size"),a.optLong("size"));return rank!=0?rank:a.optString("fid").compareTo(b.optString("fid"));});JSONObject best=bucket.get(0);kept.add(best);for(int i=1;i<bucket.size();i++){JSONObject other=bucket.get(i);Double a=duration(best),b=duration(other);boolean same=best.optString("fid").equals(other.optString("fid"))||a!=null&&b!=null&&a>=5&&b>=5&&ratio(a,b)>=.97&&ratio(best.optLong("size"),other.optLong("size"))>=.975;if(same){removed++;report.getJSONArray("groups").put("「"+best.optString("name")+"」存在同编码副本，保留清晰度较高版本。");}else{kept.add(other);report.getJSONArray("requiresReview").put("「"+best.optString("name")+"」有疑似不同版本，时长或体积不同，已全部保留。");}}}report.put("removedVideos",removed);kept.sort((a,b)->{int v=CourseTools.natural(a.optString("parentPath"),b.optString("parentPath"));if(v==0)v=CourseTools.natural(a.optString("name"),b.optString("name"));return v!=0?v:a.optString("fid").compareTo(b.optString("fid"));});return kept;
 }
 public static List<JSONObject> build(JSONObject scan)throws Exception {
  String pwd=scan.getString("pwdID"),shareTitle=scan.optString("shareTitle",scan.optString("title","网盘课程"));Map<String,Folder> folders=new LinkedHashMap<>();folders.put("",new Folder("",shareTitle,""));List<JSONObject> entries=Planner.list(scan.getJSONArray("entries"));for(JSONObject item:entries)if(item.optBoolean("isDirectory")){String path=item.getString("relativePath");folders.putIfAbsent(path,new Folder(path,item.getString("name"),item.getString("fid")));}
  for(Folder folder:new ArrayList<>(folders.values()))if(!folder.path.isEmpty()){String parent=folder.path.contains("/")?folder.path.substring(0,folder.path.lastIndexOf('/')):"";Folder owner=folders.get(parent);if(owner==null)throw new IllegalArgumentException("网盘目录不完整，请重新读取。");owner.children.add(folder);}
  for(JSONObject item:entries)if(!item.optBoolean("isDirectory")){Folder parent=folders.get(item.optString("parentPath"));if(parent==null)throw new IllegalArgumentException("网盘目录不完整。");if(video(item)&&playable(item))parent.own.add(item);else if((extension(item.optString("name")).matches(DOCUMENT)||item.optInt("category")==3||item.optInt("category")==4||item.optString("formatType").startsWith("text/")))parent.documents++;else parent.others++;}collect(folders.get(""));
  Set<String> wrappers=new HashSet<>(),chapters=new HashSet<>();for(Folder folder:folders.values()){int stages=0,count=0;for(Folder child:folder.children){if(!child.videos.isEmpty())count++;if(has(child.name,STAGES)&&!chapter(child.name)&&child.score>=.6)stages++;}if(folder.own.isEmpty()&&(stages>=2||has(folder.name,MATERIAL)&&count>=2))wrappers.add(folder.path);if(!wrappers.contains(folder.path)){int n=0;for(Folder child:folder.children)if(chapter(child.name))n++;if(n>=2)for(Folder child:folder.children)if(chapter(child.name))chapters.add(child.path);}}
  List<Folder> candidates=new ArrayList<>();for(Folder folder:folders.values()){if(folder.videos.isEmpty()||wrappers.contains(folder.path))continue;boolean suppressed=false;for(String chapter:chapters)if(folder.path.equals(chapter)||folder.path.startsWith(chapter+"/"))suppressed=true;if(suppressed)continue;if(folder.path.isEmpty()&&folder.own.isEmpty()){int chapterCount=0;for(Folder child:folder.children)if(chapter(child.name))chapterCount++;if(chapterCount<2)continue;}candidates.add(folder);}
  // Consecutive one/two-video sibling folders form a lecture series, just as on desktop.
  List<Folder> series=new ArrayList<>();Set<String> suppressedSeries=new HashSet<>();for(Folder parent:folders.values())if(parent.own.isEmpty()){Map<String,List<Folder>> groups=new LinkedHashMap<>();for(Folder child:parent.children){Matcher suffix=Pattern.compile("^(.+?)[0-9]{1,3}$").matcher(child.name.trim());if(suffix.matches()&&child.videos.size()>=1&&child.videos.size()<=2){String stem=suffix.group(1).replaceAll("^[ ._、()（）-]+|[ ._、()（）-]+$","");if(stem.length()>=2)groups.computeIfAbsent(stem,k->new ArrayList<>()).add(child);}}for(Map.Entry<String,List<Folder>> group:groups.entrySet())if(group.getValue().size()>=3){String path=parent.path.isEmpty()?group.getKey():parent.path+"/"+group.getKey();Folder combined=new Folder(path,group.getKey(),parent.fid+":series:"+group.getKey());for(Folder child:group.getValue()){combined.own.addAll(child.videos);suppressedSeries.add(child.path);}collect(combined);series.add(combined);suppressedSeries.add(parent.path);}}
  candidates.removeIf(f->{for(String path:suppressedSeries)if(f.path.equals(path)||!path.isEmpty()&&f.path.startsWith(path+"/")||!f.path.isEmpty()&&path.startsWith(f.path+"/"))return true;return false;});candidates.addAll(series);
  int strong=0;for(Folder folder:candidates)if(!folder.path.isEmpty()&&folder.score>=.6)strong++;if(strong>=2)candidates.removeIf(f->f.path.isEmpty());candidates.sort((a,b)->{int v=Double.compare(b.score,a.score);return v!=0?v:Integer.compare(b.path.split("/").length,a.path.split("/").length);});List<Folder> selected=new ArrayList<>();for(Folder f:candidates){boolean contained=false;for(Folder old:selected)if(f.path.equals(old.path)||f.path.isEmpty()||old.path.isEmpty()||f.path.startsWith(old.path+"/")||old.path.startsWith(f.path+"/"))contained=true;if(!contained)selected.add(f);}selected.sort((a,b)->CourseTools.natural(a.path,b.path));
  List<JSONObject> result=new ArrayList<>();Map<String,List<JSONObject>> videosByID=new HashMap<>();for(Folder folder:selected){JSONObject report=summary();List<JSONObject> videos=dedup(folder.videos,report);String packageID="quark:"+pwd+":"+(folder.fid.isEmpty()?"root":folder.fid);String name=folder.name;if(folder.path.contains("/")){String parent=folder.path.substring(0,folder.path.lastIndexOf('/'));String parentName=parent.substring(parent.lastIndexOf('/')+1);if(!name.contains(parentName)&&!parentName.contains(name))name=parentName+" · "+name;}List<Double> known=new ArrayList<>();for(JSONObject v:videos){Double d=duration(v);if(d!=null)known.add(d);}Collections.sort(known);int unknown=videos.size()-known.size();String refusal=known.isEmpty()?"网盘没有提供任何视频时长，无法估算学习量。":unknown>0&&known.size()<3?"缺时长的视频存在，且已知时长不足3个，无法估算学习量。":null;double median=known.isEmpty()?0:Math.max(60,known.get(known.size()/2));JSONArray lessons=new JSONArray();JSONObject metadata=new JSONObject();Set<String> ids=new HashSet<>();for(JSONObject v:videos){String id="quark:"+pwd+":"+v.getString("fid");if(!ids.add(id))throw new IllegalArgumentException("视频标识重复，请重新读取。");Double d=duration(v);lessons.put(new JSONObject().put("id",id).put("name",title(v.getString("name"))).put("subject","").put("stage","").put("chapter",v.optString("parentPath")).put("kind","video").put("published",true).put("durationSeconds",d==null?median:d).put("watchedPercent",0).put("markedFinished",false).put("requiresDuration",true));JSONObject meta=new JSONObject().put("fid",v.getString("fid")).put("path",v.getString("relativePath")).put("size",Math.max(0,v.optLong("size"))).put("estimatedDuration",d==null);for(String field:new String[]{"width","height"})if(v.has(field))meta.put(field,v.get(field));metadata.put(id,meta);}
   JSONObject snapshot=new JSONObject().put("packageID",packageID).put("name",name).put("sourceURL",scan.getString("sourceURL")).put("fetchedAt",scan.getDouble("fetchedAt")).put("expectedOutlines",1).put("fetchedOutlines",1).put("lessons",lessons).put("issues",new JSONArray());if(refusal!=null)snapshot.put("refusal",refusal);snapshot.put("netdisk",new JSONObject().put("pwdID",pwd).put("shareTitle",shareTitle).put("folderPath",folder.path).put("sourceURL",scan.getString("sourceURL")).put("fetchedAt",scan.getDouble("fetchedAt")).put("videoCount",videos.size()).put("totalBytes",bytes(videos)).put("unknownDurations",unknown).put("detection",String.format(Locale.CHINA,"课程判定 %.0f 分 · 视频 %d 个",folder.score*100,videos.size())).put("duplicates",report)).put("netdiskLessons",metadata);result.add(snapshot);videosByID.put(packageID,videos);
  }
  Set<String> dropped=new HashSet<>();for(int i=0;i<result.size();i++)for(int j=i+1;j<result.size();j++){JSONObject a=result.get(i),b=result.get(j);List<JSONObject> av=videosByID.get(a.getString("packageID")),bv=videosByID.get(b.getString("packageID"));Set<String> left=identities(av),right=identities(bv),common=new HashSet<>(left);common.retainAll(right);if(left.isEmpty()||right.isEmpty())continue;double overlap=common.size()/(double)Math.min(left.size(),right.size());double title=loose(a.getString("name")).equals(loose(b.getString("name")))?1:left.equals(right)?.5:0;double score=.62*overlap+.13*title+(.25/3)*(ratio(av.size(),bv.size())+ratio(seconds(av),seconds(bv))+ratio(bytes(av),bytes(bv)));if(overlap<.5||score<.72)continue;boolean auto=score>=.90&&Math.min(av.size(),bv.size())>=3&&left.equals(right)&&ratio(seconds(av),seconds(bv))>=.95&&ratio(bytes(av),bytes(bv))>=.85;String note="《"+a.getString("name")+"》与《"+b.getString("name")+"》课节重合 "+Math.round(overlap*100)+"%";JSONObject report=a.getJSONObject("netdisk").getJSONObject("duplicates");if(auto){JSONObject loser=bytes(av)>=bytes(bv)?b:a;dropped.add(loser.getString("packageID"));report.getJSONArray("relatedPackages").put(note+"，已保留质量较高的完整副本。");}else{report.getJSONArray("requiresReview").put(note+"，疑似版本差异，已全部保留。");b.getJSONObject("netdisk").getJSONObject("duplicates").getJSONArray("requiresReview").put(note);}}
  result.removeIf(s->dropped.contains(s.optString("packageID")));return result;
 }
 public static void compareExisting(List<JSONObject> incoming,JSONObject state)throws Exception{for(JSONObject snapshot:incoming){JSONObject report=snapshot.getJSONObject("netdisk").getJSONObject("duplicates");JSONArray existing=new JSONArray();snapshot.put("existingCourses",existing);Set<String> ids=new HashSet<>(),names=new HashSet<>();for(JSONObject lesson:Planner.list(snapshot.getJSONArray("lessons"))){ids.add(lesson.getString("id"));names.add(loose(lesson.getString("name")));}for(JSONObject course:Planner.list(state.getJSONArray("courses"))){if(course.optBoolean("isArchived"))continue;JSONObject web=course.optJSONObject("webCourse");if(web==null)continue;int same=0,named=0;for(JSONObject lesson:Planner.list(web.optJSONArray("lessons"))){if(ids.contains(lesson.optString("id")))same++;if(names.contains(loose(lesson.optString("name"))))named++;}int n=Math.min(ids.size(),web.optJSONArray("lessons").length());if(web.optString("packageID").equals(snapshot.getString("packageID"))||n>0&&(same>0||n>=3&&named/(double)n>=.8))existing.put(new JSONObject().put("id",course.getString("id")).put("name",course.getString("name")));if(web.optString("packageID").equals(snapshot.getString("packageID")))report.getJSONArray("relatedCourses").put("已有《"+course.getString("name")+"》绑定此目录，导入会更新并保留完成流水。");else if(n>0&&(same>0||n>=3&&named/(double)n>=.8))report.getJSONArray("relatedCourses").put("与已有《"+course.getString("name")+"》有相同文件或高度相似课节，请核对后选择，避免重复学习量。");}}}
 public static JSONObject merge(List<JSONObject> sources,String name)throws Exception{Set<String> unique=new HashSet<>();String share=null;for(JSONObject source:sources){String pwd=source.getJSONObject("netdisk").getString("pwdID");if(share==null)share=pwd;if(!unique.add(source.getString("packageID"))||!share.equals(pwd))throw new IllegalArgumentException("只能合并当前分享中的不同课程目录。");}if(sources.size()<2||name.trim().isEmpty())throw new IllegalArgumentException("请选择至少两门完整课程并填写合并名称。");List<String> packages=new ArrayList<>();for(JSONObject s:sources){if(s.has("refusal")||WebCourseImport.problem(s)!=null)throw new IllegalArgumentException("不能合并不完整课程。");packages.add(s.getString("packageID"));}Collections.sort(packages);StringBuilder digest=new StringBuilder();byte[] bytes=java.security.MessageDigest.getInstance("SHA-256").digest(String.join("\n",packages).getBytes(java.nio.charset.StandardCharsets.UTF_8));for(int i=0;i<16;i++)digest.append(String.format(Locale.ROOT,"%02x",bytes[i]));JSONObject first=sources.get(0),metadata=CourseTools.copy(first.getJSONObject("netdisk"));String packageID="quark:"+metadata.getString("pwdID")+":merged:"+digest;JSONArray lessons=new JSONArray();JSONObject files=new JSONObject();List<JSONObject> sorted=new ArrayList<>(sources);sorted.sort((a,b)->CourseTools.natural(a.optString("name"),b.optString("name")));int unknown=0;long totalBytes=0;Set<String> seen=new HashSet<>();for(JSONObject source:sorted)for(JSONObject raw:CourseTools.intelligent(Planner.list(source.getJSONArray("lessons"))))if(seen.add(raw.getString("id"))){JSONObject lesson=CourseTools.copy(raw);if(lesson.optString("subject").isEmpty())lesson.put("subject",source.getString("name"));lessons.put(lesson);JSONObject file=source.getJSONObject("netdiskLessons").getJSONObject(raw.getString("id"));files.put(raw.getString("id"),file);totalBytes+=file.optLong("size");if(file.optBoolean("estimatedDuration"))unknown++;}metadata.put("sourcePackageIDs",new JSONArray(packages)).put("folderPath","合并自 "+sources.size()+" 个目录").put("videoCount",lessons.length()).put("totalBytes",totalBytes).put("unknownDurations",unknown).put("duplicates",summary());return new JSONObject().put("packageID",packageID).put("name",name.trim()).put("sourceURL",first.getString("sourceURL")).put("fetchedAt",first.getDouble("fetchedAt")).put("expectedOutlines",1).put("fetchedOutlines",1).put("lessons",lessons).put("issues",new JSONArray()).put("netdisk",metadata).put("netdiskLessons",files);}
}
