package local.studyplanner;

import android.app.*;import android.content.*;import android.graphics.Typeface;import android.view.*;import android.widget.*;import android.text.*;import org.json.*;import java.time.*;import java.util.*;

/** Mobile entry points for the desktop planner features; business logic remains independently testable. */
final class PlannerFeatures {
 final MainActivity app;PlannerFeatures(MainActivity app){this.app=app;}
 void overview()throws Exception{
  app.body.addView(app.button("搜索课程或课时，查找安排日期",this::search));
  JSONArray risks=app.state.optJSONArray("androidRisks");if(risks!=null)for(JSONObject risk:Planner.list(risks)){LinearLayout box=app.card(app.body);box.addView(app.text("截止 "+Planner.date(risk.getDouble("deadline"))+" · 排程风险",16,0xffbd7418));box.addView(app.text("需要 "+risk.getInt("requiredMinutes")+" 分钟 · 可排容量 "+risk.getInt("availableMinutes")+" 分钟 · 未排入 "+risk.getInt("unscheduledMinutes")+" 分钟",13,app.ink));box.addView(app.text(risk.getJSONArray("courseNames").join("、")+"\n"+(risk.getInt("requiredMinutes")>risk.getInt("availableMinutes")?"可用时间不足，请增加时段或延后截止日期。":"总容量尚足，但连续时间块、整节课程或课间休息限制了安排，请调整时段或最小时间块。"),12,app.muted));}
  StudyLoad.Assessment load=StudyLoad.assess(app.state,Planner.now());
  if(load!=null){LinearLayout box=app.card(app.body);int tint=load.level==2?0xffbd3333:load.level==1?0xffbd7418:0xff168875;box.addView(app.text("总学习负荷 · "+new String[]{"尚有余量","时间紧张","无法按期完成"}[load.level],17,tint));box.addView(app.text(String.format(Locale.CHINA,"日均最低 %.2f 小时 · 临界日均上限 %.2f 小时",load.dailyRequired(),load.dailyCapacity()),14,app.ink));box.addView(app.text(Double.isFinite(load.utilization())?String.format(Locale.CHINA,"已占可分配时长的 %.1f%%",load.utilization()*100):"剩余容量为零",13,tint));box.addView(app.text("再不学习 "+load.warningAfter+" 天 → 时间紧张警告\n再不学习 "+load.criticalAfter+" 天 → 无法按期完成",13,app.ink));box.addView(app.text("最紧张区间："+load.start+" 至 "+load.deadline+"。按完整自然日估算，包含暂停课程；仅扣除每天重复事项。实际排程还受时间块和非每日事项影响。"+(load.limited?" 已按未来十年上限估算。":""),12,app.muted));}
  weekly();
 }
 void weekly()throws Exception{
  LocalDate monday=app.selected.minusDays(app.selected.getDayOfWeek().getValue()-1);List<JSONObject> courses=Planner.list(app.state.getJSONArray("courses"));Map<String,int[]> totals=new LinkedHashMap<>();int sum=0,max=1;
  for(JSONObject c:courses)if(!c.optBoolean("isArchived"))totals.put(c.getString("id"),new int[7]);
  for(JSONObject task:Planner.list(app.state.getJSONArray("tasks"))){int day=(int)java.time.temporal.ChronoUnit.DAYS.between(monday,Planner.day(task.getDouble("start")));int[] values=totals.get(task.optString("courseID"));if(day>=0&&day<7&&values!=null){int n=Planner.pending(task)?task.optInt("durationMinutes"):task.optInt("completedMinutes");values[day]+=n;sum+=n;}}
  for(int day=0;day<7;day++){int n=0;for(int[] values:totals.values())n+=values[day];max=Math.max(max,n);}
  LinearLayout box=app.card(app.body);box.addView(app.title("本周学习 · "+app.hours(sum)));
  for(int day=0;day<7;day++){LinearLayout row=app.row();TextView label=app.text("周"+"一二三四五六日".charAt(day),12,app.muted);row.addView(label,new LinearLayout.LayoutParams(app.dp(32),-2));LinearLayout bar=app.row();int used=0;for(JSONObject c:courses){int[] values=totals.get(c.optString("id"));int n=values==null?0:values[day];used+=n;if(n>0){View segment=new View(app);segment.setBackgroundColor(app.color(c.optString("color")));bar.addView(segment,new LinearLayout.LayoutParams(0,app.dp(8),n));}}View spacer=new View(app);bar.addView(spacer,new LinearLayout.LayoutParams(0,app.dp(8),Math.max(1,max-used)));row.addView(bar,new LinearLayout.LayoutParams(0,-2,1));TextView time=app.text(app.hours(used),11,app.muted);row.addView(time,new LinearLayout.LayoutParams(app.dp(76),-2));box.addView(row);}
  StringBuilder legend=new StringBuilder();for(JSONObject c:courses)if(totals.containsKey(c.optString("id"))){if(legend.length()>0)legend.append(" · ");legend.append(c.optString("name"));}box.addView(app.text(legend.toString(),12,app.muted));
 }
 void search(){LinearLayout form=app.col();form.setPadding(app.dp(16),0,app.dp(16),0);EditText query=app.field(form,"课程或课时关键词","",false);TextView count=app.text("搜索全部历史和未来安排，点结果跳转到当天。",12,app.muted);form.addView(count);LinearLayout rows=app.col();ScrollView scroll=new ScrollView(app);scroll.addView(rows);form.addView(scroll,new LinearLayout.LayoutParams(-1,app.dp(380)));AlertDialog dialog=new AlertDialog.Builder(app).setTitle("搜索课程日期").setView(form).setNegativeButton("关闭",null).create();
  query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int n,int after){}public void onTextChanged(CharSequence s,int start,int before,int n){rows.removeAllViews();String raw=s.toString().trim().toLowerCase(Locale.ROOT);if(raw.isEmpty()){count.setText("搜索全部历史和未来安排，点结果跳转到当天。");return;}List<JSONObject> matches=new ArrayList<>();for(JSONObject t:Planner.list(app.state.optJSONArray("tasks"))){JSONObject c=Planner.course(app.state,t.optString("courseID"));String haystack=((c==null?"":c.optString("name"))+" "+t.optString("lessonName")).toLowerCase(Locale.ROOT);boolean found=true;for(String term:raw.split("\\s+"))if(!haystack.contains(term))found=false;if(found)matches.add(t);}matches.sort(Comparator.comparingDouble(t->t.optDouble("start")));count.setText("找到 "+matches.size()+" 项安排 · 按日期排序");for(JSONObject t:matches){JSONObject c=Planner.course(app.state,t.optString("courseID"));String name=t.optString("lessonName",c==null?"已删除课程":c.optString("name"));rows.addView(app.button(Planner.date(t.optDouble("start"))+" "+Planner.clock(Planner.planningStart(t))+" · "+name+(Planner.pending(t)?" · 未确认":" · 已确认"),()->{app.selected=Planner.day(t.optDouble("start"));app.month=app.selected.withDayOfMonth(1);app.page=0;dialog.dismiss();app.render();}));}}public void afterTextChanged(Editable s){}});dialog.show();
 }
 void coursesHeader(){app.body.addView(app.button("合并课程",this::merge));app.body.addView(app.button("从网站抓取全部课程",()->app.startActivityForResult(new Intent(app,CourseImportActivity.class).putExtra("mode","website"),MainActivity.IMPORT_COURSES)));app.body.addView(app.button("从夸克网盘分享导入",()->app.startActivityForResult(new Intent(app,CourseImportActivity.class).putExtra("mode","netdisk"),MainActivity.IMPORT_COURSES)));}
 void netdiskFiles(JSONObject course){app.run(()->{JSONObject net=course.getJSONObject("netdisk"),files=course.optJSONObject("netdiskLessons");LinearLayout form=app.col(),rows=app.col();form.addView(app.text(net.optString("shareTitle")+" / "+net.optString("folderPath")+"\n"+net.optInt("videoCount")+" 个视频 · "+net.optLong("totalBytes")+" 字节 · "+net.optInt("unknownDurations")+" 个估算时长",13,app.muted));JSONObject dup=net.optJSONObject("duplicates");if(dup!=null)for(String key:new String[]{"groups","relatedPackages","relatedCourses","requiresReview"}){JSONArray notes=dup.optJSONArray(key);if(notes!=null)for(int i=0;i<notes.length();i++)form.addView(app.text(notes.getString(i),12,app.muted));}EditText query=app.field(form,"搜索课节或文件路径","",false);Runnable display=()->{rows.removeAllViews();try{String term=app.value(query).toLowerCase(Locale.ROOT);for(JSONObject lesson:CourseTools.lessons(course)){JSONObject file=files==null?null:files.optJSONObject(lesson.optString("id"));String path=file==null?"":file.optString("path");if(!(lesson.optString("name")+" "+path).toLowerCase(Locale.ROOT).contains(term))continue;rows.addView(app.text(lesson.optString("name")+"\n"+path+(file==null?"":"\n"+file.optLong("size")+" 字节 · "+(file.optBoolean("estimatedDuration")?"估算时长":"网站时长")),14,app.ink));}}catch(Exception error){app.alert("显示失败",error.getMessage());}};query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){display.run();}public void afterTextChanged(Editable s){}});ScrollView scroll=new ScrollView(app);scroll.addView(rows);form.addView(scroll,new LinearLayout.LayoutParams(-1,app.dp(360)));display.run();new AlertDialog.Builder(app).setTitle("网盘课节与文件").setView(form).setPositiveButton("关闭",null).show();});}
 void sample(){app.mutate(state->{for(String key:new String[]{"courses","fixedEvents","tasks","completions"})if(state.getJSONArray(key).length()>0)throw new IllegalArgumentException("示例仅能载入空白日程。");LocalDate day=Planner.day(Planner.now());for(int i=0;i<2;i++){JSONObject course=new JSONObject().put("id",Planner.id()).put("name",i==0?"示例 · 高等数学":"示例 · 英语基础").put("type","录播课程").put("totalMinutes",i==0?720:480).put("initialCompletedMinutes",0).put("startDate",Planner.at(day,0)).put("deadline",Planner.at(day.plusDays(14),0)).put("priority",2).put("minimumBlockMinutes",60).put("color",i==0?"blue":"purple").put("isArchived",false).put("autoScheduleEnabled",true).put("notes","这是可删除的示例课程。");state.getJSONArray("courses").put(course);}},true,null);}
 void merge(){app.run(()->{List<JSONObject> courses=Planner.list(app.state.getJSONArray("courses"));courses.removeIf(c->c.optBoolean("isArchived"));if(courses.size()<2)throw new IllegalArgumentException("请先添加至少两门课程。");LinearLayout form=app.col();Set<String> ids=new HashSet<>();EditText name=app.field(form,"合并后的课程名称","合并课程",false);for(JSONObject c:courses){CheckBox choice=new CheckBox(app);choice.setText(c.getString("name")+" · "+app.hours(Planner.remaining(app.state,c)));choice.setOnCheckedChangeListener((button,checked)->{if(checked)ids.add(c.optString("id"));else ids.remove(c.optString("id"));});form.addView(choice);}form.addView(app.text("采用最早开始日和截止日；来源、课节和完成记录迁入合并课程。",12,app.muted));form.addView(app.button("预览合并后的编排",()->app.run(()->{JSONObject next=CourseTools.copy(app.state);JSONObject merged=CourseTools.merge(next,ids,app.value(name));preview(next,merged);})));AlertDialog dialog=app.editor("合并课程",form);dialog.setOnShowListener(v->dialog.getButton(-1).setOnClickListener(x->app.mutate(s->CourseTools.merge(s,ids,app.value(name)),true,dialog::dismiss)));dialog.show();});}
 void preview(JSONObject state,JSONObject course)throws Exception{
  List<JSONObject> tasks=CourseTools.preview(state,course,Planner.now());LinearLayout rows=app.col();Map<String,Integer> booked=new HashMap<>();for(JSONObject t:tasks)booked.merge(t.optString("lessonID"),t.optInt("durationMinutes"),Integer::sum);
  int total=0;for(JSONObject t:tasks){total+=t.optInt("durationMinutes");rows.addView(app.text(Planner.date(t.getDouble("start"))+" "+Planner.clock(Planner.planningStart(t))+"–"+Planner.clock(Planner.planningEnd(t))+"\n"+t.optString("lessonName",course.optString("name"))+" · "+t.getInt("durationMinutes")+" 分钟",14,app.ink));}
  if(tasks.isEmpty())rows.addView(app.text("没有可排入的未完成课节。",14,app.muted));int remaining=Planner.remaining(state,course);rows.addView(app.text("已排 "+total+" 分钟 · 剩余 "+remaining+" 分钟 · 未排入 "+Math.max(0,remaining-total)+" 分钟",13,app.muted));ScrollView scroll=new ScrollView(app);scroll.addView(rows);new AlertDialog.Builder(app).setTitle(course.optString("name")+" · 编排预览").setView(scroll).setPositiveButton("关闭",null).show();
 }
 void lessonOrder(JSONObject course){app.run(()->{List<JSONObject> lessons=CourseTools.lessons(course);if(lessons.size()<2)throw new IllegalArgumentException("这门课程没有可调整的多个课节。");Map<String,String> names=new LinkedHashMap<>();for(JSONObject l:lessons)names.put(l.getString("id"),l.getString("name"));List<String> order=CourseTools.order(course);Set<String> selected=new HashSet<>(),movable=new HashSet<>();for(Planner.Work w:Planner.lessonWork(app.state,course))movable.add(w.lessonID);
  LinearLayout form=app.col(),rows=app.col();app.renderLessonOrderRows(rows,order,names,selected,movable);ScrollView scroll=new ScrollView(app);scroll.addView(rows);form.addView(scroll,new LinearLayout.LayoutParams(-1,app.dp(280)));EditText target=app.field(form,"插入到第几节之前（课节数 + 1 为末尾）","1",true);
  Runnable refresh=()->app.renderLessonOrderRows(rows,order,names,selected,movable);for(int position:new int[]{0,1,2}){String label=new String[]{"移到最前","移到最后","移动所选课节"}[position];form.addView(app.button(label,()->app.run(()->{int at=position==0?0:position==1?order.size():app.integer(target)-1;if(at<0||at>order.size()||selected.isEmpty())throw new IllegalArgumentException("请选择课节并填写有效序号。");List<String> moved=app.movedLessons(order,selected,at);order.clear();order.addAll(moved);refresh.run();})));}
  form.addView(app.button("智能排序",()->{order.clear();for(JSONObject l:CourseTools.intelligent(lessons))order.add(l.optString("id"));refresh.run();}));JSONObject web=course.optJSONObject("webCourse");if(web!=null)form.addView(app.button("按网站顺序",()->{order.clear();for(JSONObject l:lessons)order.add(l.optString("id"));refresh.run();}));form.addView(app.button("编排预览",()->app.run(()->preview(app.state,CourseTools.copy(course).put("lessonOrder",new JSONArray(order))))));
  AlertDialog dialog=app.editor("调整课节学习顺序",form);dialog.setOnShowListener(v->dialog.getButton(-1).setOnClickListener(x->app.mutate(s->{JSONObject current=Planner.course(s,course.getString("id"));if(current==null)throw new IllegalArgumentException("课程已删除，请刷新。");boolean follows=web!=null&&order.equals(sourceOrder(lessons));current.put("lessonOrder",new JSONArray(order)).put("lessonOrderCustomized",!follows);},true,dialog::dismiss)));dialog.show();});}
 static List<String> sourceOrder(List<JSONObject> lessons){List<String> ids=new ArrayList<>();for(JSONObject l:lessons)ids.add(l.optString("id"));return ids;}
 void taskDrag(LinearLayout box,JSONObject task){if(!Planner.pending(task)||Planner.day(task.optDouble("start")).isBefore(Planner.day(Planner.now())))return;String id=task.optString("id");box.setContentDescription("长按交换 "+task.optString("lessonName",Planner.course(app.state,task.optString("courseID")).optString("name")));box.setOnLongClickListener(view->{if(app.busy)return false;return view.startDragAndDrop(ClipData.newPlainText("daily-task",id),new View.DragShadowBuilder(view),id,0);});box.setOnDragListener((view,event)->{Object local=event.getLocalState();if(!(local instanceof String)||id.equals(local))return false;JSONObject source=null;for(JSONObject t:Planner.list(app.state.optJSONArray("tasks")))if(t.optString("id").equals(local))source=t;if(source==null||!Planner.pending(source)||!Planner.day(source.optDouble("start")).equals(Planner.day(task.optDouble("start"))))return false;
   switch(event.getAction()){case DragEvent.ACTION_DRAG_STARTED:return true;case DragEvent.ACTION_DRAG_ENTERED:box.setAlpha(.65f);return true;case DragEvent.ACTION_DRAG_EXITED:case DragEvent.ACTION_DRAG_ENDED:box.setAlpha(1);return true;case DragEvent.ACTION_DROP:box.setAlpha(1);app.swapDailyTasks((String)local,id);return true;default:return true;}});
  box.addView(app.button("交换本日顺序",()->app.run(()->{List<JSONObject> targets=new ArrayList<>();for(JSONObject other:Planner.list(app.state.getJSONArray("tasks")))if(Planner.pending(other)&&!other.getString("id").equals(id)&&Planner.day(other.getDouble("start")).equals(Planner.day(task.getDouble("start"))))targets.add(other);if(targets.isEmpty())throw new IllegalArgumentException("当天没有其他未确认学习板块。");String[] labels=new String[targets.size()];for(int i=0;i<labels.length;i++){JSONObject t=targets.get(i),c=Planner.course(app.state,t.getString("courseID"));labels[i]=Planner.clock(t.getDouble("start"))+" · "+t.optString("lessonName",c.optString("name"));}new AlertDialog.Builder(app).setTitle("选择要交换的学习板块").setItems(labels,(dialog,index)->app.swapDailyTasks(id,targets.get(index).optString("id"))).setNegativeButton("取消",null).show();})));
 }
}
