package local.studyplanner;

import org.json.*;import java.net.URI;import java.util.*;

/** Validates complete captures and reconciles website progress by lesson before saving anything. */
public final class WebCourseImport {
 public static String safeURL(String value){try{URI url=new URI(value);if(!"https".equalsIgnoreCase(url.getScheme())||url.getHost()==null)return "";String query=null,host=url.getHost().toLowerCase(Locale.ROOT);if((host.equals("ixuecheng.cn")||host.endsWith(".ixuecheng.cn"))&&"/detail".equals(url.getPath())&&url.getRawQuery()!=null){List<String> publicItems=new ArrayList<>();for(String item:url.getRawQuery().split("&")){String[] pair=item.split("=",2);if(pair.length==2&&(pair[0].equals("id")||pair[0].equals("type"))&&pair[1].matches("[A-Za-z0-9_-]{1,128}"))publicItems.add(pair[0]+"="+pair[1]);}if(!publicItems.isEmpty())query=String.join("&",publicItems);}return new URI("https",null,url.getHost(),url.getPort(),url.getPath(),query,null).toString();}catch(Exception e){return "";}}

 public static JSONObject sanitize(JSONObject raw)throws Exception{
  JSONObject snapshot=new JSONObject();for(String key:new String[]{"packageID","name","expectedOutlines","fetchedOutlines"})snapshot.put(key,raw.get(key));snapshot.put("sourceURL",safeURL(raw.optString("sourceURL"))).put("fetchedAt",raw.getDouble("fetchedAt"));JSONArray lessons=new JSONArray();for(JSONObject item:Planner.list(raw.getJSONArray("lessons"))){JSONObject lesson=new JSONObject();for(String key:new String[]{"id","name","subject","stage","chapter","kind","published","durationSeconds","watchedPercent","markedFinished","requiresDuration"})if(item.has(key))lesson.put(key,item.get(key));for(String key:new String[]{"subject","stage","chapter"})if(!lesson.has(key))lesson.put(key,"");lessons.put(lesson);}snapshot.put("lessons",lessons).put("issues",raw.optJSONArray("issues")==null?new JSONArray():raw.getJSONArray("issues"));return snapshot;
 }
 public static String problem(JSONObject snapshot){try{
  if(snapshot.getJSONArray("issues").length()>0||snapshot.getInt("expectedOutlines")!=snapshot.getInt("fetchedOutlines"))return "抓取未完成，请重试；不会把部分结果当作完整课程。";if(snapshot.optString("packageID").isEmpty()||snapshot.optString("name").trim().isEmpty()||!Double.isFinite(snapshot.getDouble("fetchedAt")))return "课程包信息不完整。";JSONArray lessons=snapshot.getJSONArray("lessons");if(lessons.length()==0)return "该课程包暂无可读取课节。";Set<String> ids=new HashSet<>();double total=0;
  for(JSONObject lesson:Planner.list(lessons)){if(lesson.optString("id").isEmpty()||!ids.add(lesson.getString("id")))return "课节标识重复或缺失，请重新抓取。";double duration=lesson.optDouble("durationSeconds",Double.NaN),percent=lesson.optDouble("watchedPercent",Double.NaN);if(lesson.optBoolean("published")&&lesson.optBoolean("requiresDuration")){if(!Double.isFinite(duration)||duration<=0)return "已发布视频缺少可验证时长，暂不能生成准确计划。";if(!Double.isFinite(percent))return "课节缺少观看进度，暂不能确定剩余量。";total+=duration;}if(lesson.has("durationSeconds")&&!lesson.isNull("durationSeconds")&&(!Double.isFinite(duration)||duration<=0||duration>36000000))return "课节时长无效。";if(lesson.has("watchedPercent")&&!lesson.isNull("watchedPercent")&&(!Double.isFinite(percent)||percent<0||percent>100))return "课节观看进度无效。";}
  if(!Double.isFinite(total)||total<=0||total>36000000)return "可排程总时长须大于零且不超过 10,000 小时。";return null;
 }catch(Exception e){return "课程数据不完整，请重新读取。";}}
 static Map<String,Integer> durations(JSONObject snapshot,boolean remaining)throws Exception{Map<String,Integer> values=new LinkedHashMap<>();double sum=0;for(JSONObject lesson:Planner.list(snapshot.getJSONArray("lessons")))if(lesson.optBoolean("published")&&lesson.optBoolean("requiresDuration")){int before=Planner.ceilMinutes(sum);sum+=lesson.getDouble("durationSeconds")*(remaining?1-lesson.getDouble("watchedPercent")/100:1);values.put(lesson.getString("id"),Planner.ceilMinutes(sum)-before);}return values;}
 public static int total(JSONObject snapshot)throws Exception{int total=0;for(int n:durations(snapshot,false).values())total+=n;return total;}
 public static int completed(JSONObject snapshot)throws Exception{int remaining=0;for(int n:durations(snapshot,true).values())remaining+=n;return total(snapshot)-remaining;}
 static JSONObject newCourse(JSONObject snapshot,double deadline,double now)throws Exception{return new JSONObject().put("id",Planner.id()).put("name",snapshot.getString("name")).put("type","不定时录播课程").put("totalMinutes",1).put("initialCompletedMinutes",0).put("startDate",now).put("deadline",deadline).put("minimumBlockMinutes",60).put("priority",2).put("color","blue").put("autoScheduleEnabled",true).put("isArchived",false).put("notes","");}
 public static JSONObject cleanCapture(JSONObject raw)throws Exception{JSONObject clean=sanitize(raw);JSONObject incoming=raw.optJSONObject("netdisk");if(incoming!=null){JSONObject net=new JSONObject();for(String key:new String[]{"pwdID","shareTitle","folderPath","fetchedAt","videoCount","totalBytes","unknownDurations","detection","sourcePackageIDs"})if(incoming.has(key))net.put(key,incoming.get(key));net.put("sourceURL",safeURL(incoming.optString("sourceURL")));JSONObject duplicate=incoming.optJSONObject("duplicates");if(duplicate!=null){JSONObject summary=new JSONObject();for(String key:new String[]{"groups","relatedPackages","relatedCourses","requiresReview"}){JSONArray notes=duplicate.optJSONArray(key),values=new JSONArray();if(notes!=null)for(int i=0;i<Math.min(5,notes.length());i++)values.put(notes.getString(i));summary.put(key,values);}summary.put("removedVideos",Math.max(0,duplicate.optInt("removedVideos")));net.put("duplicates",summary);}clean.put("netdisk",net);JSONObject files=new JSONObject(),all=raw.optJSONObject("netdiskLessons");for(JSONObject lesson:Planner.list(clean.getJSONArray("lessons"))){String id=lesson.getString("id");JSONObject original=all==null?null:all.optJSONObject(id);if(original==null)throw new IllegalArgumentException("课节文件元数据缺失。");JSONObject file=new JSONObject();for(String key:new String[]{"fid","path","size","width","height","estimatedDuration"})if(original.has(key))file.put(key,original.get(key));files.put(id,file);}clean.put("netdiskLessons",files);}return clean;}
 public static void save(JSONObject state,List<JSONObject> captures,double deadline,double now)throws Exception{
  if(captures.isEmpty())throw new IllegalArgumentException("请选择至少一门完整课程。");if(Planner.day(deadline).isBefore(Planner.day(now))||Planner.day(deadline).isAfter(Planner.day(now).plusYears(10)))throw new IllegalArgumentException("截止日期须在今天起十年以内。");JSONObject next=CourseTools.copy(state);Set<String> packages=new HashSet<>();
  for(JSONObject raw:captures){JSONObject snapshot=sanitize(raw);String problem=problem(snapshot);if(problem!=null)throw new IllegalArgumentException(snapshot.optString("name")+"："+problem);String packageID=snapshot.getString("packageID");if(!packages.add(packageID))throw new IllegalArgumentException("导入课程包重复。");List<JSONObject> matches=new ArrayList<>();for(JSONObject c:Planner.list(next.getJSONArray("courses")))if(c.optJSONObject("webCourse")!=null&&c.getJSONObject("webCourse").optString("packageID").equals(packageID))matches.add(c);if(matches.size()>1)throw new IllegalArgumentException("已有多个课程绑定同一课程包，请先整理重复课程。");JSONObject old=matches.isEmpty()?newCourse(snapshot,deadline,now):matches.get(0),updated=CourseTools.copy(old);String id=old.getString("id");int logged=0;Map<String,JSONObject> taskByID=new HashMap<>();for(JSONObject t:Planner.list(next.getJSONArray("tasks")))if(t.optString("courseID").equals(id))taskByID.put(t.getString("id"),t);List<JSONObject> records=new ArrayList<>();for(JSONObject r:Planner.list(next.getJSONArray("completions")))if(r.optString("courseID").equals(id)){records.add(r);logged+=r.getInt("minutes");}int total=total(snapshot),webCompleted=completed(snapshot);if(logged<0||logged>total)throw new IllegalArgumentException("已有完成流水超过网站课程总量，需人工核对。");
   Map<String,Integer> totals=durations(snapshot,false),remaining=durations(snapshot,true),webCredits=new HashMap<>(),localCredits=new HashMap<>(),allLocalCredits=new HashMap<>();for(String lesson:totals.keySet())webCredits.put(lesson,totals.get(lesson)-remaining.get(lesson));int unidentified=0;for(JSONObject r:records){JSONObject task=taskByID.get(r.optString("taskID"));String lesson=task==null?"":task.optString("lessonID");if(webCredits.containsKey(lesson)){allLocalCredits.merge(lesson,r.getInt("minutes"),Integer::sum);if(r.getDouble("recordedAt")<=snapshot.getDouble("fetchedAt"))localCredits.merge(lesson,r.getInt("minutes"),Integer::sum);}else if(r.getDouble("recordedAt")<=snapshot.getDouble("fetchedAt"))unidentified+=r.getInt("minutes");}
   Map<String,Integer> previousBaselines=new HashMap<>();Map<String,Integer> previousTotals=new HashMap<>();JSONObject previousWeb=old.optJSONObject("webCourse");if(previousWeb!=null)previousTotals=durations(previousWeb,false);else for(JSONObject lesson:CourseTools.lessons(old))previousTotals.put(lesson.optString("id"),lesson.optInt("durationMinutes"));for(Planner.Work w:Planner.lessonWorkAll(next,old))previousBaselines.put(w.lessonID,Math.max(0,previousTotals.getOrDefault(w.lessonID,w.minutes)-w.minutes-allLocalCredits.getOrDefault(w.lessonID,0)));
   JSONObject overlaps=new JSONObject();int identified=0;for(String lesson:localCredits.keySet()){int overlap=Math.min(localCredits.get(lesson),Math.max(0,webCredits.getOrDefault(lesson,0)-previousBaselines.getOrDefault(lesson,0)));overlaps.put(lesson,overlap);identified+=overlap;}int overlap=identified+Math.min(unidentified,Math.max(0,webCompleted-identified));updated.put("name",snapshot.getString("name")).put("type","不定时录播课程").put("totalMinutes",total).put("initialCompletedMinutes",Math.min(total-logged,Math.max(0,webCompleted-overlap))).put("webCourse",snapshot).put("webCompletionOverlaps",overlaps);
   if(old.optBoolean("isArchived"))updated.put("isArchived",false).put("autoScheduleEnabled",true).put("startDate",now).put("deadline",deadline);
   boolean follows=!old.optBoolean("lessonOrderCustomized",false);if(!old.has("lessonOrderCustomized")&&old.optJSONArray("lessonOrder")!=null&&previousWeb!=null){List<String> intelligent=new ArrayList<>();for(JSONObject lesson:CourseTools.intelligent(Planner.list(previousWeb.getJSONArray("lessons"))))intelligent.add(lesson.getString("id"));List<String> order=new ArrayList<>();for(int i=0;i<old.getJSONArray("lessonOrder").length();i++)order.add(old.getJSONArray("lessonOrder").getString(i));follows=order.equals(intelligent);}
   if(follows){List<String> order=new ArrayList<>();for(JSONObject lesson:Planner.list(snapshot.getJSONArray("lessons")))order.add(lesson.getString("id"));updated.put("lessonOrder",new JSONArray(order)).put("lessonOrderCustomized",false);}else{updated.put("lessonOrder",new JSONArray(CourseTools.order(updated)));}
   JSONObject clean=cleanCapture(raw);if(clean.optJSONObject("netdisk")!=null)updated.put("netdisk",clean.getJSONObject("netdisk")).put("netdiskLessons",clean.getJSONObject("netdiskLessons"));
   Planner.put(next.getJSONArray("courses"),updated);
  }
  state.put("courses",next.getJSONArray("courses"));
 }
}
