package local.studyplanner;

import org.json.*;import java.util.*;

/** Desktop-compatible live lesson IDs and incremental captures across catalog pages. */
public final class WebsiteCapture {
 public static JSONObject xuecheng(JSONObject catalog,List<JSONObject> base,String source,double now)throws Exception{
  String packageID="generic:"+catalog.getString("courseID");JSONArray lessons=new JSONArray();Map<String,Integer> counts=new HashMap<>();Map<String,JSONObject> known=new HashMap<>(),byID=new HashMap<>();Set<String> used=new HashSet<>();for(JSONObject snapshot:base)if(snapshot.optString("packageID").equals(packageID))for(JSONObject lesson:Planner.list(snapshot.getJSONArray("lessons"))){known.put(lesson.getString("name"),lesson);byID.put(lesson.getString("id"),lesson);}
  for(JSONObject row:Planner.list(catalog.getJSONArray("rows"))){String name=row.getString("name");int occurrence=counts.getOrDefault(name,0)+1;counts.put(name,occurrence);String key=row.optString("key",String.valueOf(occurrence)),id=packageID+":live:"+name+":"+key;JSONObject previous=byID.get(id);if(previous==null)previous=known.get(name);if(previous!=null&&!used.add(previous.optString("id")))previous=null;JSONObject lesson=new JSONObject().put("id",id).put("name",name).put("subject","").put("stage","").put("chapter","").put("kind","living").put("published",row.optBoolean("replay")).put("requiresDuration",row.optBoolean("replay")).put("markedFinished",previous!=null&&previous.optBoolean("markedFinished")).put("watchedPercent",previous==null?0:previous.optDouble("watchedPercent",0));if(previous!=null&&previous.has("durationSeconds"))lesson.put("durationSeconds",previous.get("durationSeconds"));lessons.put(lesson);}
  return new JSONObject().put("packageID",packageID).put("name",catalog.getString("name")).put("sourceURL",WebCourseImport.safeURL(source)).put("fetchedAt",now).put("expectedOutlines",1).put("fetchedOutlines",1).put("lessons",lessons).put("issues",new JSONArray());
 }
 public static List<JSONObject> merge(List<JSONObject> previous,List<JSONObject> fresh)throws Exception{
  Map<String,JSONObject> values=new LinkedHashMap<>();for(JSONObject snapshot:previous)values.put(snapshot.getString("packageID"),CourseTools.copy(snapshot));for(JSONObject raw:fresh){String packageID=raw.getString("packageID");JSONObject old=values.get(packageID),next=CourseTools.copy(raw);if(old!=null){List<JSONObject> lessons=Planner.list(old.getJSONArray("lessons"));Set<Integer> matched=new HashSet<>();for(JSONObject item:Planner.list(next.getJSONArray("lessons"))){int at=-1;for(int i=0;i<lessons.size();i++)if(lessons.get(i).getString("id").equals(item.getString("id"))){at=i;break;}if(at<0)for(int i=0;i<lessons.size();i++)if(!matched.contains(i)&&lessons.get(i).getString("name").equals(item.getString("name"))&&(lessons.get(i).optString("kind").equals("living")||item.optString("kind").equals("living"))){at=i;break;}if(at>=0){matched.add(at);JSONObject before=lessons.get(at);if(item.isNull("durationSeconds")&&before.has("durationSeconds"))item.put("durationSeconds",before.get("durationSeconds"));if((item.isNull("watchedPercent")||item.optDouble("watchedPercent")==0)&&before.optDouble("watchedPercent",0)>0)item.put("watchedPercent",before.getDouble("watchedPercent"));item.put("markedFinished",item.optBoolean("markedFinished")||before.optBoolean("markedFinished"));lessons.set(at,item);}else{matched.add(lessons.size());lessons.add(item);}}next.put("lessons",new JSONArray(lessons));}values.put(packageID,next);}return new ArrayList<>(values.values());
 }
}
