package local.studyplanner;
import org.json.*;import java.time.*;import java.util.*;

public final class DesktopParityTests {
 static final LocalDate DAY=LocalDate.of(2026,10,7);static int checks;
 static void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
 static JSONObject copy(JSONObject value)throws Exception{return new JSONObject(value.toString());}
 static List<JSONObject> pending(JSONObject state)throws Exception{List<JSONObject> result=new ArrayList<>();for(JSONObject t:Planner.list(state.getJSONArray("tasks")))if(Planner.pending(t))result.add(t);return result;}
 static JSONObject fixture()throws Exception{JSONObject state=PlannerTests.empty();state.getJSONObject("settings").put("availability",StudySettingsTests.windows(540,1320)).put("actualStudyStart",Planner.at(DAY,1101));
  int[] durations={49,69,35};int[] starts={1101,1165,1249};for(int i=0;i<3;i++){JSONObject c=PlannerTests.course("课程"+i,durations[i],DAY,DAY,durations[i]);state.getJSONArray("courses").put(c);state.getJSONArray("tasks").put(Planner.task(c.getString("id"),Planner.at(DAY,starts[i]),durations[i]).put("status","planned"));}
  JSONObject c=PlannerTests.course("历史课程",108,DAY.minusDays(1),DAY,60);state.getJSONArray("courses").put(c);JSONObject history=Planner.task(c.getString("id"),Planner.at(DAY,957),108).put("status","completed").put("completedMinutes",108).put("confirmedAt",Planner.at(DAY.minusDays(1),780)).put("floatingWindowStart",Planner.at(DAY,957)).put("floatingWindowEnd",Planner.at(DAY,1180));state.getJSONArray("tasks").put(history);state.getJSONArray("completions").put(new JSONObject().put("id",Planner.id()).put("courseID",c.getString("id")).put("taskID",history.getString("id")).put("minutes",108).put("recordedAt",history.getDouble("confirmedAt")));return state;
 }
 static void swaps()throws Exception{for(int[] pair:new int[][]{{0,1},{0,2},{1,2}}){JSONObject state=fixture();List<JSONObject> original=pending(state);String history=state.getJSONArray("tasks").getJSONObject(3).toString();List<String> ids=new ArrayList<>();for(JSONObject t:original)ids.add(t.getString("id"));DailyTaskOrdering.swap(state,ids.get(pair[0]),ids.get(pair[1]),Planner.at(DAY,1080));Collections.swap(ids,pair[0],pair[1]);List<JSONObject> tasks=pending(state);for(int i=0;i<3;i++)check(tasks.get(i).getString("id").equals(ids.get(i)),"Swap ID order lost");check(tasks.get(0).getDouble("start")==Planner.at(DAY,1101),"History incorrectly blocked evening");check(Planner.end(tasks.get(2))==Planner.at(DAY,1284),"Duration/break changed");List<String> courses=new ArrayList<>();for(JSONObject t:tasks)courses.add(t.getString("courseID"));
   for(int i=0;i<2;i++){Planner.replan(state,Planner.at(DAY,1110));List<JSONObject> again=pending(state);for(int j=0;j<3;j++)check(again.get(j).getString("courseID").equals(courses.get(j)),"Replan ignored saved dailyTaskOrders");}
   JSONObject retained=null;for(JSONObject t:Planner.list(state.getJSONArray("tasks")))if(!Planner.pending(t))retained=t;check(retained!=null&&retained.toString().equals(history),"Historical fields changed");SyncLedger ledger=new SyncLedger();ledger.capture(state);SyncLedger peer=new SyncLedger();peer.merge(ledger.changes(0));JSONObject synced=peer.materialize();Planner.replan(synced,Planner.at(DAY,1110));for(int j=0;j<3;j++)check(pending(synced).get(j).getString("courseID").equals(courses.get(j)),"Sync changed ordered day");
  }
  JSONObject state=fixture();state.getJSONArray("tasks").getJSONObject(3).put("confirmedAt",Planner.at(DAY,1120));List<JSONObject> original=pending(state);DailyTaskOrdering.swap(state,original.get(0).getString("id"),original.get(1).getString("id"),Planner.at(DAY,1125));check(pending(state).get(0).getDouble("start")==Planner.at(DAY,1135),"Actual history/break ignored");
  state=fixture();state.getJSONArray("tasks").getJSONObject(3).put("confirmedAt",Planner.at(DAY,1195));String before=state.toString();original=pending(state);try{DailyTaskOrdering.swap(state,original.get(0).getString("id"),original.get(1).getString("id"),Planner.at(DAY,1080));throw new AssertionError("No-space swap accepted");}catch(IllegalArgumentException expected){check(expected.getMessage().equals(DailyTaskOrdering.NO_SPACE),"Wrong rejection");check(state.toString().equals(before),"Rejected swap mutated state");}
 }
 static void merging()throws Exception{JSONObject state=fixture();List<JSONObject> courses=Planner.list(state.getJSONArray("courses"));Set<String> ids=new HashSet<>(Arrays.asList(courses.get(0).getString("id"),courses.get(3).getString("id")));JSONObject merged=CourseTools.merge(state,ids,"合并");check(merged.getInt("totalMinutes")==157,"Merge duration lost");check(Planner.completed(state,merged)==108,"Merge completion lost");check(merged.getJSONArray("mergedSources").length()==2,"Merge sources lost");Planner.replan(state,Planner.at(DAY,1101));Planner.validate(state);check(Planner.remaining(state,merged)==49,"Merge duplicated progress");}
 static void smart()throws Exception{List<JSONObject> rows=new ArrayList<>();for(String name:new String[]{"第十讲","第二讲（下）","第二讲（上）","第一讲"})rows.add(new JSONObject().put("id",name).put("name",name));List<JSONObject> sorted=CourseTools.intelligent(rows);check(sorted.get(0).getString("name").equals("第一讲"),"Chinese number sort failed");check(sorted.get(1).getString("name").equals("第二讲（上）"),"Part sort failed");check(sorted.get(3).getString("name").equals("第十讲"),"Natural number sort failed");}
 static void load()throws Exception{JSONObject state=PlannerTests.empty();state.getJSONObject("settings").put("availability",StudySettingsTests.windows(540,600));JSONObject course=PlannerTests.course("暂停也有截止",120,DAY,DAY.plusDays(1),60).put("autoScheduleEnabled",false);state.getJSONArray("courses").put(course);StudyLoad.Assessment load=StudyLoad.assess(state,Planner.at(DAY,1200));check(load.level==1&&load.required==120&&load.available==120,"Load boundary/pause wrong");check(load.warningAfter==0&&load.criticalAfter==1,"Skip-day estimate wrong");state.getJSONArray("courses").getJSONObject(0).put("startDate",Planner.at(DAY.plusDays(1),0));load=StudyLoad.assess(state,Planner.at(DAY,1200));check(load.level==2&&load.available==60,"Future start budget wrong");}
 static void derived()throws Exception{JSONObject state=fixture();String tasks=state.getJSONArray("tasks").toString(),settings=state.getJSONObject("settings").toString();Planner.refreshDiagnostics(state,Planner.at(DAY,1101));check(state.getJSONArray("tasks").toString().equals(tasks),"Diagnostics replaced shared plans");check(state.getJSONObject("settings").toString().equals(settings),"Diagnostics replaced shared settings");check(state.has("androidRisks")&&state.has("androidWarnings"),"Derived diagnostics absent after storage read");}
 public static void main(String[] args)throws Exception{swaps();merging();smart();load();derived();System.out.println("DesktopParityTests: "+checks+" checks passed");}
}
