package local.studyplanner;

import org.json.*;import java.time.*;import java.util.*;

/** Synthetic imports exercise refresh/undo, atomic validation, recognition and credential exclusion. */
public final class ImportParityTests {
 static int checks;static LocalDate day=LocalDate.of(2026,10,7);static double now=Planner.at(day,480),deadline=Planner.at(day.plusDays(30),0);
 static void check(boolean value,String message){checks++;if(!value)throw new AssertionError(message);}
 static JSONObject lesson(String id,double duration,double percent)throws Exception{return new JSONObject().put("id",id).put("name","第"+id+"讲").put("subject","").put("stage","").put("chapter","").put("kind","video").put("published",true).put("requiresDuration",true).put("durationSeconds",duration).put("watchedPercent",percent).put("markedFinished",false);}
 static JSONObject snapshot(double a,double b,double date)throws Exception{return new JSONObject().put("packageID","synthetic-package").put("name","测试课程").put("sourceURL","https://example.test/course?access_token=PLACEHOLDER").put("fetchedAt",date).put("expectedOutlines",1).put("fetchedOutlines",1).put("issues",new JSONArray()).put("lessons",new JSONArray().put(lesson("1",3600,a)).put(lesson("2",3600,b)));}
 static void refresh()throws Exception{JSONObject state=PlannerTests.empty();WebCourseImport.save(state,Collections.singletonList(snapshot(0,0,now)),deadline,now);JSONObject course=state.getJSONArray("courses").getJSONObject(0);String id=course.getString("id");check(course.getInt("totalMinutes")==120,"Imported duration wrong");check(course.getJSONObject("webCourse").getString("sourceURL").equals("https://example.test/course"),"Query credentials retained");JSONObject task=Planner.task(id,now,30).put("lessonID","1").put("lessonName","第一讲");state.getJSONArray("tasks").put(task);Planner.confirm(state,task.getString("id"),30,now+600);
  WebCourseImport.save(state,Collections.singletonList(snapshot(50,0,now+1200)),deadline,now+1200);course=Planner.course(state,id);check(course.getInt("initialCompletedMinutes")==0&&Planner.completed(state,course)==30,"Website/local overlap duplicated");check(Planner.lessonWork(state,course).stream().mapToInt(w->w.minutes).sum()==90,"Remaining mismatch");WebCourseImport.save(state,Collections.singletonList(snapshot(50,50,now+1800)),deadline,now+1800);course=Planner.course(state,id);check(Planner.completed(state,course)==60,"Independent lesson progress lost");check(Planner.lessonWork(state,course).stream().mapToInt(w->w.minutes).sum()==60,"Per-lesson progress mismatch");Planner.undoConfirmation(state,task.getString("id"),now+2000);course=Planner.course(state,id);check(Planner.completed(state,course)==60,"Undo lost verified website progress");
  course.put("lessonOrder",new JSONArray().put("2").put("1")).put("lessonOrderCustomized",true);JSONObject latest=snapshot(50,50,now+2400);latest.getJSONArray("lessons").put(lesson("3",1800,0));WebCourseImport.save(state,Collections.singletonList(latest),deadline,now+2400);course=Planner.course(state,id);check(course.getJSONArray("lessonOrder").toString().equals("[\"2\",\"1\",\"3\"]"),"Custom order/new lesson lost");Planner.replan(state,now+2400);Planner.validate(state);check(state.getJSONArray("courses").length()==1,"Refresh duplicated course");SyncLedger l=new SyncLedger();l.capture(state);SyncLedger peer=new SyncLedger();peer.merge(l.changes(0));check(SyncLedger.canonical(state.getJSONArray("courses")).equals(SyncLedger.canonical(peer.materialize().getJSONArray("courses"))),"Import sync changed metadata");
  String before=state.toString();JSONObject invalid=snapshot(0,0,now);invalid.put("packageID","bad").getJSONArray("lessons").getJSONObject(0).remove("durationSeconds");try{WebCourseImport.save(state,Arrays.asList(snapshot(100,100,now+3000),invalid),deadline,now);throw new AssertionError("Partial import accepted");}catch(IllegalArgumentException expected){check(state.toString().equals(before),"Rejected batch partially mutated courses");}
 }
 static void generic()throws Exception{JSONArray responses=new JSONArray().put(new JSONObject().put("url","https://example.test/api/course?token=PLACEHOLDER").put("body","{\"name\":\"数学\",\"chapters\":[{\"name\":\"第一章\",\"lessons\":[{\"id\":\"one\",\"name\":\"极限\",\"duration\":\"45:30\",\"progress\":1},{\"id\":\"two\",\"name\":\"导数\",\"duration\":\"1小时20分\",\"progress\":50}]}]}")).put(new JSONObject().put("url","https://other.test/api/course").put("body","{\"name\":\"跨源\",\"duration\":3600}"));List<JSONObject> values=GenericCourseDigest.snapshots(responses,"https://example.test/course","标题",now);check(values.size()==1,"Grouping/cross-origin wrong");JSONObject value=values.get(0);check(value.getString("name").equals("第一章"),"Outermost list grouping diverged from Mac");check(value.getJSONArray("lessons").length()==2,"Chapter treated as lesson");check(value.getJSONArray("lessons").getJSONObject(0).getDouble("watchedPercent")==1,"1% became100%");check(value.getJSONArray("lessons").getJSONObject(1).getDouble("durationSeconds")==4800,"Text duration failed");check(WebCourseImport.problem(value)==null,"Valid generic course refused");check(GenericCourseDigest.clockSeconds("01:02:03")==3723,"Clock parser failed");
  responses=new JSONArray().put(new JSONObject().put("url","https://example.test/api").put("body","{\"lessons\":[{\"id\":1,\"name\":\"第一讲\",\"courseId\":\"math\",\"courseName\":\"数学\",\"videoDuration\":3600000,\"progress\":0.5},{\"id\":2,\"name\":\"第二讲\",\"courseId\":\"math\",\"courseName\":\"数学\",\"videoDuration\":1800000,\"progress\":1}]}"));value=GenericCourseDigest.snapshots(responses,"https://example.test/course","标题",now).get(0);check(value.getJSONArray("lessons").getJSONObject(0).getDouble("durationSeconds")==3600,"Millisecond conversion failed");check(value.getJSONArray("lessons").getJSONObject(0).getDouble("watchedPercent")==50,"Ratio conversion failed");
 }
 static JSONObject folder(String name)throws Exception{return new JSONObject().put("fid","folder-"+name).put("name",name).put("relativePath",name).put("parentPath","").put("isDirectory",true);}
 static JSONObject video(String folder,String id,String name,Double seconds)throws Exception{JSONObject item=new JSONObject().put("fid",id).put("name",name+".mp4").put("relativePath",folder+"/"+name+".mp4").put("parentPath",folder).put("isDirectory",false).put("size",100000000).put("status",1).put("category",1);if(seconds!=null)item.put("durationSeconds",seconds);return item;}
 static JSONObject scan(JSONArray entries)throws Exception{return new JSONObject().put("pwdID","synthetic-share").put("shareTitle","模拟分享").put("sourceURL","https://pan.quark.cn/s/synthetic-share").put("fetchedAt",now).put("entries",entries);}
 static void netdisk()throws Exception{JSONArray entries=new JSONArray();for(String stage:new String[]{"基础课程","强化课程"}){entries.put(folder(stage));for(int i=1;i<=4;i++)entries.put(video(stage,stage+i,"第"+i+"讲 · "+stage,i==4?null:600.0+i*60));}List<JSONObject> values=NetdiskImport.build(scan(entries));check(values.size()==2,"Stage directories swallowed");for(JSONObject value:values){check(!value.has("refusal")&&WebCourseImport.problem(value)==null,"Median-estimated course refused");check(value.getJSONObject("netdisk").getInt("unknownDurations")==1,"Missing-duration count wrong");check(value.getJSONArray("lessons").getJSONObject(3).getDouble("durationSeconds")==720,"Median duration wrong");}
  JSONObject merged=NetdiskImport.merge(values,"合并");JSONObject reversed=NetdiskImport.merge(Arrays.asList(values.get(1),values.get(0)),"重新命名");check(merged.getString("packageID").equals(reversed.getString("packageID")),"Merged identity depends on selection order/name");check(merged.getJSONArray("lessons").length()==8,"Merge lost videos");JSONObject state=PlannerTests.empty();merged.put("stoken","PLACEHOLDER");JSONObject file=merged.getJSONObject("netdiskLessons").getJSONObject(merged.getJSONArray("lessons").getJSONObject(0).getString("id"));file.put("shareToken","PLACEHOLDER");WebCourseImport.save(state,Collections.singletonList(merged),deadline,now);String saved=state.toString();check(!saved.contains("stoken")&&!saved.contains("shareToken")&&!saved.contains("PLACEHOLDER"),"Transient credentials persisted");Planner.validate(state);
  entries=new JSONArray().put(folder("视频课程")).put(video("视频课程","a","第一讲",600.0)).put(video("视频课程","b","第二讲",600.0)).put(video("视频课程","c","第三讲",null));values=NetdiskImport.build(scan(entries));check(values.get(0).has("refusal"),"Too few durations estimated");
  entries=new JSONArray().put(folder("视频课程")).put(video("视频课程","a","第一讲 1080p",600.0).put("height",1080).put("width",1920)).put(video("视频课程","b","第一讲 720p",600.0).put("height",720).put("width",1280)).put(video("视频课程","c","第二讲",600.0)).put(video("视频课程","d","第三讲",600.0));values=NetdiskImport.build(scan(entries));check(values.get(0).getJSONArray("lessons").length()==3,"Exact-copy dedup failed");check(values.get(0).getJSONObject("netdisk").getJSONObject("duplicates").getInt("removedVideos")==1,"Dedup summary lost");
 }
 static void seriesAndExisting()throws Exception{JSONArray entries=new JSONArray();for(int i=1;i<=3;i++){String folder="高数视频"+i;entries.put(folder(folder)).put(video(folder,"series"+i,"第"+i+"讲 极限",600.0));}List<JSONObject> values=NetdiskImport.build(scan(entries));check(values.size()==1&&values.get(0).getJSONArray("lessons").length()==3,"Consecutive lecture folders split into separate courses");check(values.get(0).getString("packageID").contains(":series:"),"Series identity lost");JSONObject state=PlannerTests.empty();WebCourseImport.save(state,values,deadline,now);NetdiskImport.compareExisting(values,state);check(values.get(0).getJSONArray("existingCourses").length()==1,"Existing course navigation missing");check(values.get(0).getJSONObject("netdisk").getJSONObject("duplicates").getJSONArray("relatedCourses").length()==1,"Existing duplicate warning missing");JSONObject clean=WebCourseImport.cleanCapture(values.get(0));check(!clean.has("existingCourses"),"Temporary navigation references persisted");
  JSONObject snapshot=values.get(0);snapshot.getJSONObject("netdisk").getJSONObject("duplicates").put("stoken","PLACEHOLDER");JSONObject record=WebCourseImport.cleanCapture(snapshot);check(!record.toString().contains("stoken"),"Unknown nested credential metadata retained");
 }
 public static void main(String[] args)throws Exception{refresh();generic();netdisk();seriesAndExisting();System.out.println("ImportParityTests: "+checks+" checks passed");if(args.length>0){JSONObject state=PlannerTests.empty();state.getJSONObject("settings").put("availability",StudySettingsTests.windows(480,1320)).put("actualStudyStart",now);WebCourseImport.save(state,Collections.singletonList(snapshot(50,0,now)),deadline,now);List<JSONObject> net=NetdiskImport.build(scan(new JSONArray().put(folder("视频课程")).put(video("视频课程","a","第一讲",600.0)).put(video("视频课程","b","第二讲",600.0)).put(video("视频课程","c","第三讲",600.0))));WebCourseImport.save(state,net,deadline,now);for(JSONObject course:Planner.list(state.getJSONArray("courses")))course.put("deadline",Planner.at(day,0));Planner.replan(state,now);List<JSONObject> tasks=new ArrayList<>();for(JSONObject t:Planner.list(state.getJSONArray("tasks")))if(Planner.pending(t)&&Planner.day(t.getDouble("start")).equals(day))tasks.add(t);if(tasks.size()>1)DailyTaskOrdering.swap(state,tasks.get(0).getString("id"),tasks.get(1).getString("id"),now);java.nio.file.Files.write(java.nio.file.Paths.get(args[0]),state.toString(2).getBytes(java.nio.charset.StandardCharsets.UTF_8));}}
}
