package local.studyplanner;
import org.json.*;import java.nio.file.*;import java.time.*;import java.util.*;
public class PlannerTests {
 static int checks=0; static void check(boolean b,String message){checks++;if(!b)throw new AssertionError(message);}
 static JSONObject clone(JSONObject s)throws Exception{return new JSONObject(s.toString());}
 static JSONObject empty()throws Exception{return new JSONObject("{\"schemaVersion\":1,\"courses\":[],\"fixedEvents\":[],\"tasks\":[],\"completions\":[],\"settings\":{\"minimumScheduleUnit\":60,\"notificationMinute\":1260,\"availability\":[]}}");}
 static JSONObject course(String name,int total,LocalDate start,LocalDate deadline,int unit)throws Exception{return new JSONObject().put("id",Planner.id()).put("name",name).put("totalMinutes",total).put("initialCompletedMinutes",0).put("startDate",Planner.at(start,0)).put("deadline",Planner.at(deadline,0)).put("minimumBlockMinutes",unit).put("priority",2).put("autoScheduleEnabled",true).put("isArchived",false);}
 static void invariant(JSONObject s,double now)throws Exception{
  List<JSONObject> tasks=new ArrayList<>();for(JSONObject t:Planner.list(s.getJSONArray("tasks")))if(Planner.pending(t)&&t.getDouble("start")>=now)tasks.add(t);tasks.sort(Comparator.comparingDouble(t->t.optDouble("start")));
  for(int i=0;i<tasks.size();i++){JSONObject t=tasks.get(i),c=Planner.course(s,t.getString("courseID"));LocalDate day=Planner.day(t.getDouble("start"));check(Planner.eligible(c,day),"Outside course dates");if(i>0)check(Planner.end(tasks.get(i-1))<=t.getDouble("start"),"Tasks overlap");for(JSONObject e:Planner.list(s.getJSONArray("fixedEvents")))if(Planner.occurs(e,day))check(t.getDouble("start")>=Planner.at(day,e.getInt("endMinute"))||Planner.end(t)<=Planner.at(day,e.getInt("startMinute")),"Fixed overlap");boolean fits=false;List<Planner.Span> windows=new ArrayList<>();for(JSONObject a:Planner.list(s.getJSONObject("settings").getJSONArray("availability")))if(a.getInt("weekday")==Planner.weekday(day))windows.add(new Planner.Span(Planner.at(day,a.getInt("startMinute")),Planner.at(day,a.getInt("endMinute"))));for(Planner.Span w:Planner.merge(windows))if(t.getDouble("start")>=w.a&&Planner.end(t)<=w.b)fits=true;check(fits,"Outside available windows");}
  for(JSONObject c:Planner.list(s.getJSONArray("courses"))){int planned=0;for(JSONObject t:tasks)if(t.getString("courseID").equals(c.getString("id")))planned+=t.getInt("durationMinutes");for(JSONObject t:Planner.list(s.getJSONArray("tasks")))if(Planner.pending(t)&&t.getDouble("start")<now&&Planner.end(t)>now&&t.getString("courseID").equals(c.getString("id")))planned+=t.getInt("durationMinutes");check(planned<=Planner.remaining(s,c),"Overallocated learning amount");}
 }
 public static void main(String[] args)throws Exception{
  JSONObject initial=new JSONObject(new String(Files.readAllBytes(Paths.get("Android/assets/initial-state.json")),"UTF-8"));Planner.validate(initial);check(initial.getJSONArray("courses").length()==0,"Initial package includes courses");check(initial.getJSONArray("fixedEvents").length()==0,"Initial package includes fixed events");check(initial.getJSONArray("tasks").length()==0,"Initial package includes tasks");check(initial.getJSONArray("completions").length()==0,"Initial package includes completion records");
  LocalDate today=LocalDate.of(2026,9,18);double now=Planner.at(today,18*60+10);JSONObject s=empty();for(int w=1;w<=7;w++)s.getJSONObject("settings").getJSONArray("availability").put(new JSONObject().put("id",Planner.id()).put("weekday",w).put("startMinute",480).put("endMinute",1320));for(int c=0;c<4;c++)s.getJSONArray("courses").put(course("测试课程"+c,600,today.minusDays(1),today.plusDays(7+c),60));Planner.replan(s,now);Map<String,String> historical=new HashMap<>();for(JSONObject t:Planner.list(s.getJSONArray("tasks")))if(t.getDouble("start")<now||!Planner.pending(t))historical.put(t.getString("id"),t.toString());long start=System.nanoTime();Planner.replan(s,now);System.out.println("Scenario replan ms: "+(System.nanoTime()-start)/1e6);invariant(s,now);for(JSONObject t:Planner.list(s.getJSONArray("tasks")))if(historical.containsKey(t.getString("id")))check(t.toString().equals(historical.get(t.getString("id"))),"History modified");
  Files.write(Paths.get("Android/build/java-replanned.json"),s.toString().getBytes("UTF-8"));
  JSONObject chosen=null;for(JSONObject t:Planner.list(s.getJSONArray("tasks")))if(Planner.pending(t)&&t.getDouble("start")>now){chosen=t;break;}String tid=chosen.getString("id"),cid=chosen.getString("courseID");int before=Planner.completed(s,Planner.course(s,cid)),amount=chosen.getInt("durationMinutes")/2;Planner.confirm(s,tid,amount,now);check(Planner.completed(s,Planner.course(s,cid))==before+amount,"Partial credit");boolean refused=false;try{Planner.confirm(s,tid,amount,now);}catch(Exception ex){refused=true;}check(refused,"Duplicate confirmation allowed");Planner.undoConfirmation(s,tid,now);check(Planner.completed(s,Planner.course(s,cid))==before,"Undo did not restore progress");check(Planner.pending(chosen),"Undo did not restore task");boolean recordLeft=false;for(JSONObject record:Planner.list(s.getJSONArray("completions")))if(record.optString("taskID").equals(tid))recordLeft=true;check(!recordLeft,"Undo left completion record");refused=false;try{Planner.undoConfirmation(s,tid,now);}catch(Exception ex){refused=true;}check(refused,"Duplicate undo allowed");Planner.replan(s,now);invariant(s,now);
  Random random=new Random(431);for(int run=0;run<50;run++){JSONObject f=empty();for(int w=1;w<=7;w++)f.getJSONObject("settings").getJSONArray("availability").put(new JSONObject().put("id",Planner.id()).put("weekday",w).put("startMinute",480).put("endMinute",720)).put(new JSONObject().put("id",Planner.id()).put("weekday",w).put("startMinute",780).put("endMinute",1080));for(int c=0;c<4;c++)f.getJSONArray("courses").put(course("C"+c,random.nextInt(4000)+1,today.plusDays(random.nextInt(3)),today.plusDays(5+random.nextInt(10)),new int[]{30,60,90}[random.nextInt(3)]));f.getJSONArray("fixedEvents").put(new JSONObject().put("id",Planner.id()).put("title","固定").put("startMinute",600).put("endMinute",660).put("startDate",Planner.at(today,0)).put("endDate",Planner.at(today.plusDays(20),0)).put("weekdays",new JSONArray("[2,4,6]")));Planner.replan(f,Planner.at(today,480));invariant(f,Planner.at(today,480));}
  JSONObject noTime=empty();noTime.getJSONArray("courses").put(course("无可用日",100,today,today.plusDays(2),60));check(!Planner.replan(noTime,now).isEmpty(),"No capacity warning");check(noTime.getJSONArray("tasks").length()==0,"Tasks without capacity");
  JSONObject one=empty();one.getJSONArray("courses").put(course("最后余量",61,today,today,60));one.getJSONObject("settings").getJSONArray("availability").put(new JSONObject().put("id",Planner.id()).put("weekday",Planner.weekday(today)).put("startMinute",480).put("endMinute",720));Planner.replan(one,Planner.at(today,480));check(one.getJSONArray("tasks").length()==2,"Tail block missing");JSONObject first=one.getJSONArray("tasks").getJSONObject(0);Planner.confirm(one,first.getString("id"),0,Planner.at(today,480));check(Planner.remaining(one,one.getJSONArray("courses").getJSONObject(0))==61,"Missed added debt");
  JSONObject events=empty();JSONObject e=new JSONObject().put("id",Planner.id()).put("title","午休").put("startMinute",720).put("endMinute",780).put("startDate",Planner.at(today.minusDays(10),0)).put("endDate",Planner.at(today.plusDays(10),0)).put("weekdays",new JSONArray("[1,2,3,4,5,6,7]"));events.getJSONArray("fixedEvents").put(e);JSONObject edit=clone(e).put("endMinute",800);Planner.saveEvent(events,edit,now);check(events.getJSONArray("fixedEvents").length()==2,"Recurring history not split");check(Planner.occurs(e,today),"Today's started rule lost");check(!Planner.occurs(edit,today),"Edited started rule");check(Planner.occurs(edit,today.plusDays(1)),"Future rule absent");boolean conflict=false;try{Planner.saveEvent(events,clone(edit).put("id",Planner.id()),now);}catch(Exception ex){conflict=true;}check(conflict,"Fixed conflict accepted");Planner.removeEvent(events,edit.getString("id"),now);check(events.getJSONArray("fixedEvents").length()==1,"Remove future");
  JSONObject archived=clone(s);for(JSONObject c:Planner.list(archived.getJSONArray("courses")))c.put("isArchived",true);Planner.replan(archived,now);for(JSONObject t:Planner.list(archived.getJSONArray("tasks")))check(t.getDouble("start")<now||!Planner.pending(t),"Archived future task");
  System.out.println("PASS "+checks+" checks: snapshot, invariants in 50 scenarios, partial/missed/duplicate confirmations, history, recurrence conflicts, tail blocks, archive, no capacity.");
 }
}
