package local.studyplanner;
import android.app.Instrumentation;import android.os.Bundle;import android.content.*;
import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.security.cert.*;import java.util.*;import java.util.concurrent.*;import javax.net.ssl.*;

public class SyncInstrumentation extends Instrumentation {
    boolean bridge=false;int checks=0;ExecutorService worker;SyncServer server;PlannerDatabase db;Context context;String pin,token;List<String> logs=Collections.synchronizedList(new ArrayList<>());
    void check(boolean ok,String message){checks++;if(!ok)throw new AssertionError(message);}
    public void onCreate(Bundle args){super.onCreate(args);bridge=args!=null&&"true".equals(args.getString("bridge"));start();}
    public void onStart(){Bundle result=new Bundle();try{runTests();result.putString("stream","\nPASS "+checks+" device checks: SQLite transactions, TLS pinning, pairing, authorization, incrementals, interruption, deduplication, auto gate, port and worker teardown.\n");finish(-1,result);}catch(Throwable e){StringWriter out=new StringWriter();e.printStackTrace(new PrintWriter(out));out.append("\nServer logs: ").append(logs.toString());result.putString("stream",out.toString());finish(1,result);}finally{if(server!=null)server.close();if(worker!=null)worker.shutdownNow();if(db!=null)db.close();}}
    void waitWindow(boolean pairing)throws Exception{long end=System.currentTimeMillis()+15000;while(System.currentTimeMillis()<end){if(server.isRunning()&&(!pairing||!server.pairingText().isEmpty())){if(pairing)return;try(Socket s=new Socket()){s.connect(new InetSocketAddress("127.0.0.1",8765),100);return;}catch(IOException ignored){}}Thread.sleep(30);}throw new AssertionError("window unavailable");}
    void startWindow(boolean pairing,int seconds)throws Exception{server=new SyncServer(context,db,worker,logs::add,()->{},seconds);server.start(pairing,true);if(pairing)waitWindow(true);else{long end=System.currentTimeMillis()+5000;while(logs.isEmpty()||!logs.get(logs.size()-1).contains("等待 Mac")){if(System.currentTimeMillis()>end)throw new AssertionError("window start timeout");Thread.sleep(25);}}}
    void startQrWindow(String secret,int seconds)throws Exception{server=new SyncServer(context,db,worker,logs::add,()->{},seconds);server.startPairing(secret,true);long end=System.currentTimeMillis()+15000;while(System.currentTimeMillis()<end){if(server.isRunning()&&logs.stream().anyMatch(s->s.contains("二维码已验证")))return;Thread.sleep(30);}throw new AssertionError("QR pairing window unavailable");}
    void stopped()throws Exception{long end=System.currentTimeMillis()+5000;while(server.isRunning()&&System.currentTimeMillis()<end)Thread.sleep(20);check(!server.isRunning(),"server still running");Thread.sleep(100);boolean refused=false;try(Socket s=new Socket()){s.connect(new InetSocketAddress("127.0.0.1",8765),200);}catch(IOException expected){refused=true;}check(refused,"port remains open");check(Thread.getAllStackTraces().keySet().stream().noneMatch(t->t.isAlive()&&t.getName().startsWith("planner-sync-")),"sync thread remains alive");}
    static String hash(byte[] bytes)throws Exception{StringBuilder s=new StringBuilder();for(byte b:MessageDigest.getInstance("SHA-256").digest(bytes))s.append(String.format(Locale.ROOT,"%02x",b&255));return s.toString();}
    String certificatePin()throws Exception{KeyStore keys=KeyStore.getInstance("AndroidKeyStore");keys.load(null);return hash(keys.getCertificate("planner-sync-tls-v1").getEncoded());}
    JSONObject post(String path,JSONObject data,String auth)throws Exception{
        SSLContext ssl=SSLContext.getInstance("TLSv1.2");ssl.init(null,new TrustManager[]{new X509TrustManager(){public X509Certificate[] getAcceptedIssuers(){return new X509Certificate[0];}public void checkClientTrusted(X509Certificate[] c,String a)throws CertificateException{throw new CertificateException();}public void checkServerTrusted(X509Certificate[] c,String a)throws CertificateException{try{if(!hash(c[0].getEncoded()).equals(pin))throw new CertificateException("pin mismatch");}catch(Exception e){throw new CertificateException(e);}}}},new SecureRandom());
        HttpsURLConnection c=(HttpsURLConnection)new URL("https://127.0.0.1:8765/sync/"+path).openConnection();c.setSSLSocketFactory(ssl.getSocketFactory());c.setHostnameVerifier((h,s)->h.equals("127.0.0.1"));c.setConnectTimeout(3000);c.setReadTimeout(10000);c.setRequestMethod("POST");c.setRequestProperty("Authorization","Bearer "+auth);c.setRequestProperty("Connection","close");c.setDoOutput(true);byte[] b=data.toString().getBytes(StandardCharsets.UTF_8);c.setFixedLengthStreamingMode(b.length);try{try(OutputStream out=c.getOutputStream()){out.write(b);}if(c.getResponseCode()!=200)throw new IOException("HTTP "+c.getResponseCode());return new JSONObject(MainActivity.read(c.getInputStream()));}finally{c.disconnect();}
    }
    void runTests()throws Exception{
        KeyStore keys=KeyStore.getInstance("AndroidKeyStore");keys.load(null);keys.deleteEntry("planner-sync-tls-v1");
        Context target=getTargetContext();context=new ContextWrapper(target){@Override public SharedPreferences getSharedPreferences(String name,int mode){return super.getSharedPreferences("instrumentation-"+name,mode);}};
        context.getSharedPreferences("local-sync",0).edit().clear().commit();target.deleteDatabase("sync-instrumentation.db");db=new PlannerDatabase(target,"sync-instrumentation.db");worker=Executors.newSingleThreadExecutor();
        JSONObject initial=new JSONObject(MainActivity.read(target.getAssets().open("initial-state.json")));JSONObject seed=new JSONObject().put("id",Planner.id()).put("name","Device fixture").put("type","录播课程").put("totalMinutes",600).put("initialCompletedMinutes",0).put("startDate",Planner.at(java.time.LocalDate.now(Planner.ZONE),0)).put("deadline",Planner.at(java.time.LocalDate.now(Planner.ZONE).plusDays(7),0)).put("minimumBlockMinutes",60).put("priority",2).put("color","blue").put("notes","").put("autoScheduleEnabled",true).put("isArchived",false);initial.getJSONArray("courses").put(seed);Planner.replan(initial,Planner.now());db.save(initial);check(db.load().getJSONArray("tasks").length()>0,"fixture replan lost tasks");db.close();db=new PlannerDatabase(target,"sync-instrumentation.db");check(db.load().getJSONArray("courses").length()==1,"database reopen failed");
        if(bridge){
            String secret=String.join("",Collections.nCopies(32,"a1"));startQrWindow(secret,120);String ticket="studyplanner://pair?v=2&secret="+secret+"&expires="+(System.currentTimeMillis()/1000+300);java.io.File pairFile=new java.io.File(target.getExternalFilesDir(null),"sync-test-pairing.txt");try(FileOutputStream out=new FileOutputStream(pairFile)){out.write(ticket.getBytes(StandardCharsets.UTF_8));}
            long limit=System.currentTimeMillis()+120000;while(server.isRunning()&&System.currentTimeMillis()<limit)Thread.sleep(100);stopped();return;
        }
        SyncLedger mac=new SyncLedger();mac.value.put("device","MAC-TEST");mac.merge(db.ledger().changes(0));JSONObject state=mac.materialize();JSONObject added=new JSONObject(state.getJSONArray("courses").getJSONObject(0).toString()).put("id",Planner.id()).put("name","Offline Mac test").put("autoScheduleEnabled",false);state.getJSONArray("courses").put(added);mac.capture(state);
        String pairSecret=String.join("",Collections.nCopies(32,"b2"));String qr="studyplanner://pair?v=2&secret="+pairSecret+"&expires="+(System.currentTimeMillis()/1000+300);check(MainActivity.pairingSecret(qr).equals(pairSecret),"QR payload rejected");
        boolean badQr=false;try{MainActivity.pairingSecret("studyplanner://pair?v=2&secret=short&expires=1");}catch(Exception expected){badQr=true;}check(badQr,"invalid QR payload accepted");
        startQrWindow(pairSecret,30);pin=certificatePin();JSONObject paired=post("pair",new JSONObject().put("code",pairSecret),"");token=paired.getString("token");check(token.length()>32,"weak pairing token");
        String date=java.time.LocalDate.now(Planner.ZONE).toString();JSONObject request=new JSONObject().put("protocol",1).put("cursor",0).put("automatic",true).put("date",date).put("changes",mac.changes(0));
        JSONObject reply=post("changes",request,token);check(db.load().getJSONArray("courses").length()==2,"Mac addition not applied");mac.merge(reply.getJSONArray("changes"));check(mac.materialize().getJSONArray("courses").length()==2,"Android changes not received");long revision=db.ledger().sequence();
        reply=post("changes",request,token);check(db.ledger().sequence()==revision,"repeat causes duplicate changes");server.close();stopped();
        Thread.sleep(100);startWindow(false,30);reply=post("changes",request,token);check(db.ledger().sequence()==revision,"interrupted retry changed data");post("finish",new JSONObject().put("session",reply.getString("session")),token);stopped();check(db.ledger().value.getString("lastAutoDate").equals(date),"auto date not persisted");
        Thread.sleep(100);server.start(false,false);Thread.sleep(150);check(!server.isRunning(),"same-day auto reopened server");
        startWindow(false,30);boolean rejected=false;try{post("changes",request,"wrong-token");}catch(Exception e){rejected=true;}check(rejected,"unauthorized request accepted");stopped();check(db.ledger().sequence()==revision,"unauthorized mutation");
        SyncLedger before=db.ledger();JSONObject bad=new JSONObject(before.changes(0).getJSONObject(0).toString()).put("payload","bm90IGpzb24=").put("version",before.value.getLong("clock")+100);
        JSONObject invalid=new JSONObject(request.toString()).put("changes",new JSONArray().put(bad));rejected=false;try{db.exchange(invalid);}catch(Exception e){rejected=true;}check(rejected,"malformed payload accepted");check(db.ledger().sequence()==revision,"failed transaction altered database");
        startWindow(false,2);Thread.sleep(2300);stopped();
        startWindow(false,30);String correct=pin;pin=String.join("",Collections.nCopies(64,"0"));rejected=false;try{post("changes",request,token);}catch(Exception e){rejected=true;}pin=correct;check(rejected,"wrong certificate pin accepted");stopped();
        // Concurrent confirmations must credit one task only, using the winning task's payload.
        SyncLedger left=db.ledger(),right=new SyncLedger(new JSONObject(left.value.toString()));right.value.put("device","ZZZ-TEST");JSONObject ls=left.materialize(),rs=right.materialize();JSONObject task=null;for(JSONObject t:Planner.list(ls.getJSONArray("tasks")))if(Planner.pending(t)){task=t;break;}
        String taskID=task.getString("id");Planner.confirm(ls,taskID,0,Planner.now());Planner.confirm(rs,taskID,Math.min(10,task.getInt("durationMinutes")),Planner.now());left.capture(ls);right.capture(rs);left.merge(right.changes(0));JSONObject merged=left.materialize();PlannerDatabase.reconcileConfirmations(merged);int count=0;for(JSONObject c:Planner.list(merged.getJSONArray("completions")))if(c.getString("taskID").equals(taskID))count++;check(count==1,"concurrent confirmation credited twice");
        JSONObject duplicates=db.load();JSONObject duplicate=new JSONObject(duplicates.getJSONArray("tasks").getJSONObject(0).toString()).put("id",Planner.id());duplicates.getJSONArray("tasks").put(duplicate);SyncLedger duplicateLedger=db.ledger();duplicateLedger.capture(duplicates);int duplicateCount=duplicates.getJSONArray("tasks").length();PlannerDatabase.reconcileTasks(duplicateLedger,duplicates);check(duplicates.getJSONArray("tasks").length()==duplicateCount-1,"legacy IDs leave duplicate historical task");
        check(logs.stream().anyMatch(s->s.contains("网络模块关闭")),"no cleanup audit");
    }
}
